### ISSUE TITLE
Schedule times that cross midnight

### ISSUE THREAD

**Issue by artlab23** [pihome-shc/pihome#10]
schedule_add.php allows user to enter a schedule that crosses midnight (e.g. from 22:00 to 02:00), but doesn't get returned if it's past midnight (01:00) by the query in boiler.php 

`$query = "SELECT * FROM schedule_daily_time_zone_view WHERE CURTIME() between `start` AND `end` AND zone_id = {$zone_id} AND time_status = '1' LIMIT 1;";`

CURTIME is absolute, while the schedule times are relative, so past midnight the query takes the 'start' time to be after the 'end' time and (thankfully) returns nothing.

Solutions?:  I'm wondering if inserting a 'fake' end and start time either side of midnight might do it - end at 23:59:59 and insert a new schedule from 00:00:00 - or just curtail the users ability to enter end times   that don't fall between the start time and 23:59:59 and make them aware of the limitation, so they can do it manually.  Thoughts?

(I'm not sure how 'night climate' works in this regard, either)

Here's the graph that alerted me to this issue:
![scheduledvsactualtemp](https://user-images.githubusercontent.com/45641285/50000785-8961db80-ff92-11e8-9722-e68769369d67.png)

**Comment by pihome-shc** [comment]
@artlab23 i know about this issue for long time, but never got around to find solution to this, my head is melted at this stage need to find free time to get some sleep first. i just noticed something in your graph image i.e. target temperature and actual temperature,  i was trying to add day/night time as gray background, can you share this,

**Comment by artlab23** [comment]
Paulcsf's [fix](https://github.com/pihome-shc/pihome/pull/14) for the midnight roll-over issue seems to work (I tested it)... will need the query in homelist.php on line 78 updated likewise (I haven't tested that).

My graph above is me trying to visualise the schedule (work in progress, I'll share fully when it works properly - I'd like to do the input via flot).  The grey shading is (your) boiler start/stop time markings, the schedule is just 'start' times and the set temperature - flot options set to "steps: true" (my schedules run back to back with no gaps, so I didn't need to worry about 'end' times)...  to get around the schedule times being relative (times of day, rather than datetime) I just created an extra array of the schedule times/temps but one day back, then used concat to join the two data sets in flot:

`$query = "SELECT start, zone_id, temperature FROM schedule_daily_time_zone_view WHERE zone_id = 33 ORDER BY start ASC ";
$result = $conn->query($query);
//create array of pairs of x and y values
$CH_schedule_graph = array();
while ($row = mysqli_fetch_assoc($result)) {
    $CH_schedule_graph[] = array(strtotime($row['start']) * 1000, $row['temperature']); 
    $CH_schedule_graph_yday[] = array((strtotime($row['start']) * 1000) - 86400000, $row['temperature']); 
}`

`var CH_schedule_graph_yday =   <?php echo json_encode($CH_schedule_graph_yday); ?>;
var CH_schedule_graph =   <?php echo json_encode($CH_schedule_graph); ?>;

var dataset_CH_sch = 
[{
  	label: "CH", 
	data: CH_schedule_graph_yday.concat(CH_schedule_graph),
 	color: "#ff3333",
  	lines: { show: true, lineWidth: 1, steps: true, fill: true, 
	fillColor: { colors: [{ opacity: 0 }, { opacity: 1}] }, }
}`
 Crude and clunky, but it worked.

  Just prior to Paulcsf's fix, I had schedules running up to 23:59 and then from 00:01, so it graphed that OK... now I'll have to look at it all over again, as I think at one point I did some cludgey thing assigning zero temp values to 'end' times... can't find it now, though.

I did have your daylight markings working at one point, but dropped it when I realised that you can only have one set of markings on each flot plot (boiler start/stop is more useful)... I've currently got a temp probe on the exhaust of the boiler to get 'actual' run times (rather than just demand), by 'thresholding' that to either >/< 30 degs (so >30 =  50, <30 = 0, for instance) then plotting that the normal way, you can get it to look like 'markings', with the added advantage of being able to specify colour gradients, etc
Cheers, have a good sleep! :)
