### ISSUE TITLE
Boost Time bug

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/pihome#115]
When boost is triggered for one zone let say 30 minutes with 23c, and then you trigger boost for another zone with higher time 60 minutes with 40c is only take time from first boost and turns off boost for second zone as well with first one. which seems bug in the boost

**Comment by dvdcut** [comment]
@pihome-shc, i just tested it and it is working fine for me, not sure what else can be done,

**Comment by pihome-shc** [comment]
@dvdcut, you are right, this bug if fixed somehow, anyway i m closing this issue.
