### ISSUE TITLE
Nodes Add/Delete

### ISSUE THREAD

**Issue by twa127** [pihome-shc/pihome#116]
The delete node button does not appear to do anything and neither does the save button on the add node screen.

**Comment by pihome-shc** [comment]
I just tested it and working for me, I think you need to update database.

**Comment by twa127** [comment]
Used the current setup_db.php to create a test dB and still no go

**Comment by pihome-shc** [comment]
I didn’t try that script, i m using updatedb in musql folder.

**Comment by pihome-shc** [comment]
@twa127 just did one test with setup_db.php and it is worked for me, 
MaridaDB 103.17
PHP version 7.3.11-1~deb10u1

**Comment by twa127** [comment]
Thanks I’ll keep trying and let you know

**Comment by twa127** [comment]
Still not working, perhaps foreign key constraints ?

**Comment by twa127** [comment]
PHP 7.3.11-1~deb10u1 (cli) (built: Oct 26 2019 14:14:18) ( NTS )
Server version: 10.3.17-MariaDB-0+deb10u1 Raspbian 10

**Comment by pihome-shc** [comment]
Any errors?

**Comment by twa127** [comment]
for some reason it is not picking up the javascript reference, for example clicking on the delete icon fails to find the function delete_node. I can fix by adding <script type="text/javascript" src="js/request.js"></script> at the top of model.php

**Comment by pihome-shc** [comment]
js/request.js is referenced in other part of model as well, any else works that need request.js?

**Comment by twa127** [comment]
Yes true, boost works fine and the code block is similar, tried moving the node code to before the boost section, this did not help

**Comment by twa127** [comment]
It works fine in Internet Explorer and Safari but does not work in MS Edge (latest version)

**Comment by twa127** [comment]
Solved - cleared the MS Edge browser history, now all okay
