### ISSUE TITLE
Zone - Add/Edit 

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/pihome#124]
When adding zone, it set to zone temperature sensors id to 0 and zone controller only show boiler controller from drop down list. 

#69 - Missing save button on Zone edit

**Comment by MindaugasMeskauskas** [comment]
I probably could check this tomorrow if no one else already doing so.

**Comment by pihome-shc** [comment]
Zone Add/Edit is fixed from my last update but if you have free time may be test these changes. second part of this bug is when you edit the zone it add another entry in message_out table.

**Comment by pihome-shc** [comment]
closing this issue
