### ISSUE TITLE
GPIO for Zone and Boiler

### ISSUE THREAD

**Issue by sandreialexandru** [pihome-shc/pihome#126]
Changing and creating zone with GPIO is very confusing when selecting node id for GPIO. Same for boiler when selecting GPIO for boiler. 
When creating GPIO node notice interval is set to 30, change this to 0 when node is created by default. 

By default some GPIO pins are set to IN and they must be set to OUT. `gpio mode <pin> out`

**Comment by dvdcut** [comment]
i see what is happening here, i think i manage to simulate same issue, if you have multiple gpio nodes created in Zone and boiler controller you get multiple options each presented by 0. this is node id set for gpio and child id is actual pin.  
i think in zone edit and add it needs to change with some ajax where user select what type of controller they have and based on section user get one field for GPIO and I2C relay (i think at this time only these two are supported alternate) and if user select Wireless then two input fields appear one for controller id and second for child id. 
from history i see  @paulcsf did some ajax work for weather. may be we can ask his help for this as well.

**Comment by pihome-shc** [comment]
My knowledge of ajax is dependent on google. But if someone have better or different idea then you are welcome to share here.

**Comment by paulcsf** [comment]
I started looking at this, but I think it needs to wait until #123 is finished.

**Comment by pihome-shc** [comment]
this issue is closed and all required changes are in place.
