### ISSUE TITLE
Hysterezis Time

### ISSUE THREAD

**Issue by sandreialexandru** [pihome-shc/pihome#127]
Redundant hysteresis_time for zone and boiler. The problem appears if selecting a smaller hysteresis for zone than the histeresis set for boiler.

**Comment by pihome-shc** [comment]
@sandreialexandru right now histeresis time isn't implemented for zone its only implemented for boiler.

**Comment by sandreialexandru** [comment]
What about hysteresis_time in 'zone' table and hysteresis field at zone creation? Am I missing something?
Forgive my ignorance!

**Comment by pihome-shc** [comment]
@sandreialexandru 
Zone hysteresis time isnt implemented anywhere and if we were to implement then we have to take boiler hysteresis time into consideration i.e if zone is set to 5 minuts and boiler to 3 and if boiler is triggered earlier then heating and pressure in the system will build up and that isnt good. 
On other hand some zone valves (really old ones) mechanical parts can be damaged by turn on and then off and then on in short time but remember cron job runs once every 60 seconds and it is my observation that 60 seconds for zone valve is more then enough and this hysteresis_time for zone can be dropped it, i think its not required. i m open for corrections

**Comment by pihome-shc** [comment]
Closing as not further action required at this time.
