### ISSUE TITLE
Inversed logic

### ISSUE THREAD

**Issue by sandreialexandru** [pihome-shc/pihome#128]
Most boilers require a closed circuit to turn on heating. This means that a boiler connected to a Normal Open relay would be OFF in normal state. When triggering the relay the circuit gets closed and the boiler turns ON.
Having security in mind and assuming that the SD card or the Raspberry Pi could get faulty then the relay would close the NC contacts and the boiler would turn ON indefinitely. I suggest an inverse logic in _/cron/boiler.php_
**_$relay_on = '1'; //GPIO value to write to turn on attached relay
$relay_off = '0'; // GPIO value to write to turn off attached relay_**

**Comment by dvdcut** [comment]
i think this is down to relay board you are using, You need to have relay with optocoupler as descried in [pihome website ](http://www.pihome.eu/2017/10/12/wireless-arduino-boiler-controller-relay-with-nrf24l01/)
this way if pi dies or sd card or any other thing then this relay gets turned off.

**Comment by sandreialexandru** [comment]
Turning the relay off while the boiler is connected to NC contacts just puts the boiler to ON

**Comment by MindaugasMeskauskas** [comment]
@sandreialexandru  
Common standard relays have 3 contacts. 
COM = common contact
NC = normally closed contact
NO = normally open contact

In our case if you disconnect signal wires from relay it should switch off (COM + NC = off when no signal) 
Switch wires between NC and NO or change relay you have.

**Comment by sandreialexandru** [comment]
@MindaugasMeskauskas 
I'm very aware of how relays (electromagnetic or with transistor optocoupler) work. But inversing the logic would make PiHOME possible to be used with any kind of relays.

**Comment by dvdcut** [comment]
two variables at the top of boiler.php to modify values as your needs. sorry not trying to be hard but if your boiler work different then you have to swap variable values so PiHome is always in control. 

```
$relay_on = '1'; //GPIO value to write to turn on attached relay
$relay_off = '0'; // GPIO value to write to turn off attached relay
```

**Comment by MindaugasMeskauskas** [comment]
I got now what was asked, but think reversing logic is done when compiling Arduino Sketch - PiHome_Boiler_Controller_v031.ino
`#define RELAY_ON 1  // GPIO value to write to turn on attached relay`
`#define RELAY_OFF 0 // GPIO value to write to turn off attached relay`

**Comment by dvdcut** [comment]
i think @sandreialexandru was asking for raspberry pi gpio pin,

**Comment by sandreialexandru** [comment]
After searching for a while to be sure that almost everywhere, all boilers and thermostats work on the same principle I've found some discussions stating that boilers get connected to COM+NO pins of relay. If we do this with PiHOME everything works backwards.
[https://www.tyrrellsmarthome.com/wp-content/uploads/2018/02/Thermostat-Energy-Combo-Bundle.pdf](url)
[https://diy.stackexchange.com/questions/115954/isolation-relay-for-ecobee-smart-thermostat-nc-or-no](url)

**Comment by pihome-shc** [comment]
I think its worth testing this on raspberry pi just to be sure, i can do this later and update here the results.

**Comment by sandreialexandru** [comment]
I have tested this by redefining the two variables in boiler.php
$relay_on = '1'; //GPIO value to write to turn on attached relay
$relay_off = '0'; // GPIO value to write to turn off attached relay

**Comment by pihome-shc** [comment]
@sandreialexandru so if pihome set relay to 1 ($relay_on = '1';) it mean really would be on and if pi fails relay will turn off as there is no signal? 
you dont need to unplug power to pi cable but you can unplug signal cable from pi to relay board.

**Comment by aszumski** [comment]
@sandreialexandru I think most of optoisolated 5v relay boards that people use activate relay when you pull it down input to 0V. Just adjust relay on/off variables as you wish. For example I have zone valves wired to pi via relay board but I use uln2803 between relay board and pi (don't like idea of driving 5v input with 3.3v) that changes the on/off logic, so I just adjusted the script for my needs.

**Comment by harvybob** [comment]
Would the values for this be better in a config file?(like you guys have done for the database connection details) that way it's kept for the individual, and not over written on upgrade? For me using i2c I need 1 for on, but for others it will be 0 for on depending on the relay used...

**Comment by pihome-shc** [comment]
may be best to give option to user during creation of nodes i.e define on state of relay with dropdown 1 or 0 save it to database as it would be easy maintain and update.

**Comment by pihome-shc** [comment]
closing this issue.
