### ISSUE TITLE
Faster boiler response

### ISSUE THREAD

**Issue by sandreialexandru** [pihome-shc/pihome#130]
Running boiler.php faster by duplicating the cron job and delaying one of them by 30 seconds could get a faster response in boiler actions. 
Having hysteresis set at 3 minutes means that boiler cron is 1/3 of that time, which in my opinion is pretty high.
Solution:
`*/1 * * * * /usr/bin/php /var/www/cron/boiler.php >/dev/null 2>&1

*/1 * * * * **sleep 30;** /usr/bin/php /var/www/cron/boiler.php >/dev/null 2>&1`

Not a great improvement, but on the same principle, cron jobs could be tripled and delayed by 20 seconds.

**Comment by MindaugasMeskauskas** [comment]
Why you need to turn boiled on/off more often then once per minute? boiler.php currently with default crontab runs every minute and it checks hysteresis time before turning boiler again. Set hysteresis to 0 if you want it respond quicker. If you use Gas boiler it requires some time for cool off procedure after turning it off. Its not healthy power it on/off too often. For testing/debuging you can run boiler.php script from terminal at any time you want.

**Comment by pihome-shc** [comment]
@sandreialexandru why you want to run boiler.php every 30 seconds? is there any reason? may be we can find alternate if you have some requirements to run this cronjob every 30 second.

**Comment by sandreialexandru** [comment]
@MindaugasMeskauskas 
I am aware of what hysteresis means and you are right that it is a security feature. For example I've seen  pellet boilers that need a certain time to shutdown. In those cases the hysteresis should be at least the time needed by the boiler to completely power off. Having hysteresis set to 0 contradicts what you state.

@pihome-shc 
Running boiler.php faster just means that the thermostat is more responsive. Testing other thermostats (non-smart) got me to the conclusion that they react instantly (if temperature is met). I personally do not need something specific, but I thought that this could be an improvement.

Again...if someone sets hysteresis to 1 minute + 1 minute boiler cron = double the waiting time. I don't think that anyone would get too cold or too hot during that extra minute, but everyone would enjoy the instantaneous response.

Maybe I should wear the DUMB hat.

**Comment by pihome-shc** [comment]
@sandreialexandru running boiler.php every 30 second sill generate extra read/write to already undress stressed sd card. just remember all commercial solution needs 2 to 3 minuts to trigger boiler and PiHome is already step ahead. if there is no special need i can add your line in crontab and comment out and if someone need this fast response they can do this them self. 

`*/1 * * * * sleep 30; /usr/bin/php /var/www/cron/boiler.php >/dev/null 2>&1`

**Comment by aszumski** [comment]
Another thing is you get better chance of triggering cron job before previous one is finished if you have many zones, sd reads/writes are slow.
I think anyone that needs faster response can edit cron, no need to change anything.
