### ISSUE TITLE
Reorganising Settings Menu

### ISSUE THREAD

**Issue by MindaugasMeskauskas** [pihome-shc/pihome#132]
As @pihome-shc have mentioned in another post list of icons in settings menu keeps growing.
Open this issue to discussion how we could tackle this.

Example suggestions:
- Systems °, OS Version, PIHome Update, Uptime, Wifi, Ethernet, etc. could be added to one "system" menu under one icon as all just displays info. Maybe reboot and shutdown buttons added to it as well as they are relevant to the system.

- Once of confit of temperature units, language, time zone, etc., should be grouped under "First Startup".

- Or icons could be grouped like "One Touch" button on home screen  

> i was looking at the ever growing list of icons under settings. i was thinking to put these settings under language or system or perhaps another icon for time-zone?

_Originally posted by @pihome-shc in https://github.com/pihome-shc/pihome/issues/121#issuecomment-583626295_

**Comment by pihome-shc** [comment]
@MindaugasMeskauskas 
Setting icons can be organised same as Temperature Graphs,  Daily usage, Boiler Usage (data-toggle), i m open to suggestions, i thin merging these icons requires decent amount of work and it will be easy for future addition for example i m thinking to make raspberry pi as access point if no wifi/ethernet available and give user option to configure Wi-Fi from settings. 

### PiHome
PiHome Update
MQTT
PiConnect
Boost
Backup

### Systems 
OS Version
Uptime
Wi-fi
Ethernet
User Account
Cron Jobs
Services


### Setup
Override
Frost
Units
Language
Graph
Boiler
Node
Sensors
Zone 
Gateway
OpenWeather

**Comment by pihome-shc** [comment]
may be its time to implement permission. i.e normal user dont need to see or change anything and some maintenance user account with higher power.

**Comment by twa127** [comment]
I like that idea, user able to do scheduling, boost, override, holidays etc but not add zones, change units, language etc or even user not able to access the settings menu at all

**Comment by dvdcut** [comment]
i m in favor of hiding some icons and only allow users with some sort of higher permission. bit like any other home alarm, where engineer have different code to access all options and home users some other options.

**Comment by twa127** [comment]
Anyone want to try this and see what you think

[settingslist.zip](https://github.com/pihome-shc/pihome/files/4306624/settingslist.zip)

**Comment by dvdcut** [comment]
that looks good, here is my version but can not get it to work properly so i think yours would better. 



[settingslist.zip](https://github.com/pihome-shc/pihome/files/4306969/settingslist.zip)

**Comment by twa127** [comment]
Hi,

Looks like we were thinking on the same lines. 

I did not know whether to allow the selected sub-menu to stay open or close it when another menu is chosen as you have done.

**Comment by dvdcut** [comment]
i think it will be confusing for ordinary people at first glance, may be best to hide first set of icons when displaying second, third or fourth, my version still have problems as you can see its hiding but not moving icons up next to displayed icons.

**Comment by twa127** [comment]
dvdcut - attached your version mixed with mine
[settingslist.zip](https://github.com/pihome-shc/pihome/files/4308585/settingslist.zip)

**Comment by pihome-shc** [comment]
@twa127 / @dvdcut 
As always great work. few suggestions: change those icons as @twa127 had them in his version, add two <br>after icons list, add default load icon where you had shutdown, reboot and thank you icon. also worth adding one line description for each category

**Comment by twa127** [comment]
update my version
[settingslist.zip](https://github.com/pihome-shc/pihome/files/4308798/settingslist.zip)

**Comment by twa127** [comment]
what will default load do?

**Comment by pihome-shc** [comment]
@twa127 
i think your version mixed with @dvdcut  version looks lot better and with that i can not see shutdown, reboot and thank you icon.

**Comment by twa127** [comment]
Update with a bit of help text when hovering over icons.
[settingslist.zip](https://github.com/pihome-shc/pihome/files/4308911/settingslist.zip)

**Comment by pihome-shc** [comment]
@twa127 / @dvdcut 
i have combined your ideas into this, see what you both think and if happy can you do pull request. 
[settingslist.zip](https://github.com/pihome-shc/pihome/files/4315144/settingslist.zip)

**Comment by twa127** [comment]
Looks good to me

**Comment by twa127** [comment]
Just a thought - why not enter settings with all sub menus closed. Also I don’t think shutdown and reboot sit logically in the status menu, which is why I left them on the main settings screen.

**Comment by pihome-shc** [comment]
Yes, that is good idea, lets do that then.

**Comment by dvdcut** [comment]
i love the way it worked out, @twa127 is right shutdown and reboot do not sit in status, i made some improvements to @pihome-shc combined version. i m happy with this


[settingslist.zip](https://github.com/pihome-shc/pihome/files/4317645/settingslist.zip)

**Comment by twa127** [comment]
I've tidied up a bit, left thanks in the status menu and added the following lines to en.php:

$lang['tooltip_1'] = "System Status Displays";
$lang['tooltip_2'] = "System Configuration Menus";
$lang['tooltip_3'] = "Boiler Configuration Menus";
$lang['tooltip_4'] = "Node and Zone Configuation";
$lang['system_status'] = "System Status";
$lang['system_configuration'] = "System Configuration";
$lang['boiler_configuration'] = "Boiler Configuation";
$lang['node_zone_configuration'] = "Node and Zone Configuation";

[settingslist.zip](https://github.com/pihome-shc/pihome/files/4319093/settingslist.zip)

**Comment by pihome-shc** [comment]
great work, can you do pull request for this now, i think its ready to be implemented.

**Comment by MindaugasMeskauskas** [comment]
Works nicely, well done.
But have one observation, tab icons are too small for small touchscreen devices. Tried to fix, but I'm not good with CSS.

**Comment by twa127** [comment]
Latest version has slightly larger icons, is that better

**Comment by twa127** [comment]
Hi,

I was thinking that 'Services' might be better in the System Configuration menu as now both the MQTT and Amazon Echo services can be configured here
