### ISSUE TITLE
Temperature Sensor Nodes with No Assigned Controller

### ISSUE THREAD

**Issue by twa127** [pihome-shc/pihome#134]
I have a number of Temperature Sensor Nodes which are not used to control zone valves, hence it makes sense to leave controler_id and controler_child_id set to NULL.

In order to graph these nodes a change is required for zone_view to display these rows, also the Zone Modal will need a change to tidy up the display

**Comment by pihome-shc** [comment]
you can always create zone but dont enable it while creating and this way you'll have zone with real sensor without any controll over it and it would be available in schedule etc.

**Comment by twa127** [comment]
Thanks that work fine
