### ISSUE TITLE
Sensor & boiler.php problems

### ISSUE THREAD

**Issue by sandreialexandru** [pihome-shc/pihome#136]
After the recent updates, I've decided to rebuild my system from scratch, but I'm having a few problems. Can anyone please test to see if problem can be replicated or it's just me?
**1**. I'm using MySensors Ethernet gateway and only one temperature sensor (node_id = 10). The sensor is getting updated in database but not present in GUI 
![2020-02-20 173611](https://user-images.githubusercontent.com/45868553/74952391-d946f880-5408-11ea-9bad-660c64575bb0.png)

![2020-02-20 173611-3](https://user-images.githubusercontent.com/45868553/74952436-ec59c880-5408-11ea-9b76-5638aeed088e.png)

Also, notice_interval is being set to 30 by default.
**2**. boiler.php runs with errors, and as I'm not a PHP guru, I'm asking here for help.
![2020-02-20 173611-2](https://user-images.githubusercontent.com/45868553/74952638-35118180-5409-11ea-978f-867253e8855b.png)

**Comment by MindaugasMeskauskas** [comment]
@sandreialexandru 
1. in nodes table i see your node "name" is "temperature senso". seen this before could be bug. in mean time manually fix it. let us know if that was it.
2. looks like all your zones in zone_view are with status = 1

**Comment by sandreialexandru** [comment]
@MindaugasMeskauskas
You're right! Everything is working. Thank you!
After spelling check in database I could create a zone and boiler.php has no errors.
But...why did the temperature sensor got created twice? (id 25 & 26)

**Comment by MindaugasMeskauskas** [comment]
@sandreialexandru 
found issue in wifigw.py I edited recently. now could you try delete nodes 25 and 26 from db and restart node. does it still add 2 nodes?

**Comment by sandreialexandru** [comment]
Modified wifigw.py at lines 196 and 205 but it's the same! Two nodes again.

**Comment by sandreialexandru** [comment]
![image](https://user-images.githubusercontent.com/45868553/74959066-9c7fff00-5412-11ea-8853-fda341d43ce3.png)

Having another problem after modifying wifigw.py.

**Comment by sandreialexandru** [comment]
Zone sensor_id got changed to 0 which is GPIO controller and those temperatures were from Pi CPU

**Comment by MindaugasMeskauskas** [comment]
@sandreialexandru 
wrong temperature? show your message_in table.
your zone temperature node could be set to 0 which is raspberry pi temperature

**Comment by sandreialexandru** [comment]
Tested again. Same problem, two sensors with the same node_id are created.

**Comment by MindaugasMeskauskas** [comment]
unfortunately have no ethernet or wifi GW to debug this scenario, but will check when back at home if possible to reproduce with serialgw.py, as code is nearly the same.

**Comment by pihome-shc** [comment]
@sandreialexandru is this issue need any further investigation? can i help in any way? i have Ethernet & wifi gateway
