### ISSUE TITLE
Language Setting from Database

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/pihome#138]
Right now, there is no way to checking language setting from database, as language list is growing we better change it as all list can be added to index.php or to header.php.

**Comment by twa127** [comment]
I have a solution for this, will pick up the list of available languages for the contents of the languages sub-directory. Will wait until pending commit is actioned

**Comment by pihome-shc** [comment]
@twa127 interesting solution and good thinking.

**Comment by pihome-shc** [comment]
@twa127 this is really great, i take that next language will automatically picked up without modifying any code? should we remove language list form setting drop down header?

**Comment by twa127** [comment]
Hi,

Yes that’s the idea. I guess we don’t need the header dropdown selection, as either done at login or from Languages setting option

**Comment by twa127** [comment]
Just a thought - should all the language files contain the same set of $lang['lang_xx'] = "abc" entries where "abc" is the name of the language in that language ie English in English, Français in French etc?

The idea being if you were going to select French as the language you would probably be French and expect it to be spelt Français

**Comment by pihome-shc** [comment]
@twa127 yes that is right but recent updates made it all over the place,

**Comment by pihome-shc** [comment]
@twa127 after your #153 access to login page presenting blank page.

**Comment by pihome-shc** [comment]
@twa127 great work.
