### ISSUE TITLE
Add Nodes

### ISSUE THREAD

**Issue by twa127** [pihome-shc/pihome#147]
Hi,

Was thinking if there is only ever going to be 1 GPIO controller, we could suppress the node_id field in Add Nodes

**Comment by pihome-shc** [comment]
I know few people are using rpi zero w as zone and boiler controller, like multiple pi setup, I know we don’t have any way of identifying all rpi as individuals but current setup one step closer

**Comment by twa127** [comment]
Okay, so best leave as it is for now with the ability to have multiple GPIO nodes.
