### ISSUE TITLE
Gateway Python Script -Bug

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/pihome#159]
i think since merge of serial and Ethernet gateway there is problem with script. in older version as soon as sent status to change to 0 in messages_out gateway script send message but in new version its not the case. messages_out sit there until message from sensor arrives. 
@MindaugasMeskauskas worked on this may be there is something simple solution or script is stuck in loop for waiting for message to arrive before it process messages to go out. 

https://github.com/pihome-shc/pihome/blob/master/cron/gateway.py

**Comment by dvdcut** [comment]
@twa127 
python script run in loop, i remember in older version the moment i changed sent to 0 it send out message but now script sit there until message from one of the sensors arrives, i think problem is in timout, its not working or not timing out. 

in_str = gw.read_until('\n', timeout=1) # Here is receiving part of the code for Wifi

**Comment by pihome-shc** [comment]
@dvdcut i haven't look into this since @MindaugasMeskauskas changed it. i know older version send out message as soon as you set the sent column to 0.

**Comment by pihome-shc** [comment]
here is the link for read until, i think timeout not working. 

> **Telnet.read_until(expected, timeout=None)**
> Read until a given byte string, expected, is encountered or until timeout seconds have passed.
> When no match is found, return whatever is available instead, possibly empty bytes. Raise EOFError if the connection is closed and no cooked data is available.
> 

https://docs.python.org/3/library/telnetlib.html#telnetlib.Telnet.read_until

**Comment by twa127** [comment]
I've tried with all the input message code removed and confirm that the code does not read from the message out queue.

I've managed to fix by adding the database connect on entry to the while loop ie
_**while 1:
## Outgoing messages
           con = mdb.connect(dbhost, dbuser, dbpass, dbname)
           cur = con.cursor()**_

I can't understand why this is needed as the connection has already been made earlier in the code, but it appears to fix the problem.

Please test

**Comment by twa127** [comment]
I've tried with all the input message code removed and confirm that the code does not read from the message out queue.

I've managed to fix by adding the database connect on entry to the while loop ie

while 1:
## Outgoing messages
           con = mdb.connect(dbhost, dbuser, dbpass, dbname)
           cur = con.cursor()

I can't understand why this is needed as the connection has already been made earlier in the code, but it appears to fix the problem.

Please test

**Comment by dvdcut** [comment]
@twa127 
Yes, adding two lines in while loop fixed it.

**Comment by twa127** [comment]
That's the way it was before @MindaugasMeskauskas changed it, but still can't understand why they need to be there, strange

**Comment by dvdcut** [comment]
i test with your changes and resources consumption is same as before.

**Comment by twa127** [comment]
so sounds like a fix then

**Comment by twa127** [comment]
Think I've got to the bottom of it :-)

What is actually need before running the query to test if sent = 0 is to ensure that any outstanding database updates are applied, so we don't need the 2 lines:

con = mdb.connect(dbhost, dbuser, dbpass, dbname)
cur = con.cursor()

a single con.commit() will do the job

This makes more sense as con and cur had already been established
