### ISSUE TITLE
Version and Build Number

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/pihome#162]
Opening this issue to discuss with you guys about version. 
i was thinking that each time there is pull request we only update build number and version number stay the same until next release. what your opening on this version number and build numbers would be? secondly each pull request should have issue attached to it so all discussion goes that issue rather then pull request itself but again i m just asking which way is best way?

**Comment by dvdcut** [comment]
if each pull request include build number then we will have problem. what if we have two requests at same time? i think its best if you add build date after every pull request. this way it will stay consistence. 
on version number it should stay same until new version is released on github and all pull requests gets recorded in every new release. 

ps i m not developer i m just hobbyist and github is not my class and dont know how to manage software development.

**Comment by pihome-shc** [comment]
@dvdcut i m not developer either so every day is a school day for me. i think i need to explore some options how to manage this, youtube here is come :)

**Comment by dvdcut** [comment]
i think after @twa127 great work we can agree version and build number should comes from db_config.ini
also it mean each pull request should have new build number ?

**Comment by twa127** [comment]
perhaps we could use a separate file for the version and build number eg v_b.ini and just update that with every commit

**Comment by dvdcut** [comment]
i think leaving version and build in same file as db it would be easy to read while deploying database and this information is only read once deployment and then update.

**Comment by twa127** [comment]
Sounds okay to me

**Comment by pihome-shc** [comment]
so its final now, we'll lave version and build number in db_config.ini and use this info during update/installation time. Version number stay the same until next release and build number gets to pull date. 
Thank you all.
