### ISSUE TITLE
Gateway Script

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/pihome#217]
after rebooting my home router it decided to assign different ip address to my wifi gateway, previously it was fine as script check failed connection from gateway_log table and it failures were more then 9 times in last 101 minuts then it will start to search for gateway on the network. 
i think the issue is with 
pid_start_time is set to char and pid_datetime column is set to timestamp but it is empty hence the query to count the gateway failure isnt working 

`select count(*) as cnt from gateway_logs where pid_datetime >= DATE_SUB(NOW(), INTERVAL 10 MINUTE);`

**Comment by dvdcut** [comment]
after going through the history for check_gw.php i think i can answer this and fix would be easy enough, pid_datetime is set to timestamp but because removing default values from all the database caused this issue.  
on same note  db_cleanup.php depends on pid_datetime as well. this date-time stored in pid_datetime only refer to when record was updated so i m going to use php time to add record for this.

**Comment by pihome-shc** [comment]
@dvdcut thank you, great work,
