### ISSUE TITLE
WiringPi alternat to access GPIO

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/pihome#219]
As we all know well enough now, wiringpi is deprecated and i suggest we look for alternate for this anyone else willing to work on this?

Link to [wiringpi ](http://wiringpi.com/wiringpi-deprecated/)
[wiringPi updated to 2.52 for the Raspberry Pi 4B](http://wiringpi.com/wiringpi-updated-to-2-52-for-the-raspberry-pi-4b/)

**Comment by twa127** [comment]
How about calling a python function with pin number and on/off as parameters and then use RPi.GPIO in the python function to set the pin number state

**Comment by twa127** [comment]
or for example a GPIO zone controller

# setup an output pin
exec("echo '".$zone_controler_child_id."' > /sys/class/gpio/export")
exec("echo 'out' > /sys/class/gpio/gpio".$zone_controler_child_id."/direction")
# set state
exec("echo '".$zone_status."' /sys/class/gpio/gpio".$zone_controler_child_id."value")

**Comment by pihome-shc** [comment]
Python would be better option no doubt about it. But we users whi decide to move on from wiringpi needs to modify their zone/boiler information

**Comment by twa127** [comment]
All it would need is the python function and then change each of the 2 lines in boiler.php which switch the relay to a single line calling the python. I'll code and send it to you for testing

**Comment by twa127** [comment]
Please try attached, same principle as i2c relay. Need new directory /var/www/cron/gpio

[boiler.zip](https://github.com/pihome-shc/pihome/files/4532703/boiler.zip)

**Comment by pihome-shc** [comment]
is it compatible with all versions of RPI? what about pin numbering ?

**Comment by twa127** [comment]
I've used in the past on a v2 Rpi and just tested on a v3+, don't have v4 to try. 

Pin numbering can be BOARD or BCM, I've set as BCM to make compatible with current database numbering.

**Comment by twa127** [comment]
If you wanted it to be Pi Zero compatible it could be done using the gpiozero library

**Comment by pihome-shc** [comment]
using python library make all rpi version compatible or different library required for different rpi?

**Comment by twa127** [comment]
Will work across all versions except Zero but does WiringPi work with Zero and would you run PiHome on a Zero anyway

**Comment by pihome-shc** [comment]
i haven't tried pi zero with wiringpi, i have made all in one pcb (gateway, zone and boiler controller) tested it for day, didnt do full test with gpio pins. 

![2020-04-06 23 31 35](https://user-images.githubusercontent.com/33334232/80284239-403ca280-8715-11ea-84ea-a20794de06b0.jpg)

**Comment by twa127** [comment]
Will the zero have enough bandwidth to run the database?

The python 2 GPIO library is a bit on the old side, which was why I asked about Python 3. I can do the GPIO pin control in python 3 with new library based on CircuitPython, see https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi
Called from boiler.php in the same way as for python 2 version. Could also do the i2C relay using the same method. Downside is that you need to install pip3 and the 2 python 3 libraries required

**Comment by pihome-shc** [comment]
Yes, pi zero worked without any issues, I think sd card would expire first. 

Lets get python updated and move on from wiringpi

**Comment by twa127** [comment]
okay, can you test this please, you need to install the libraries first, gpio3_relay.py goes in the gpio directory -

sudo apt install python3-pip
sudo pip3 install RPI.GPIO
sudo pip3 install adafruit-blinka

[gpio3.zip](https://github.com/pihome-shc/pihome/files/4533555/gpio3.zip)

**Comment by pihome-shc** [comment]
@twa127 sorry for late reply, i have tested your script with following two rpi models: 

**Raspberry pi 3B**
```
model name      : ARMv7 Processor rev 4 (v7l)
Hardware        : BCM2835
Revision        : a02082
Model           : Raspberry Pi 3 Model B Rev 1.2
```
**Raspberry pi 4**
```
model name      : ARMv7 Processor rev 3 (v7l)
Hardware        : BCM2835
Revision        : b03111
Model           : Raspberry Pi 4 Model B Rev 1.1
```

with small change to boiler.php line 443 

```exec("python3 /var/www/cron/gpio/gpio3_relay.py ".$zone_controler_child_id." ".$zone_status);```
change to 
```exec("python3 /var/www/cron/gpio/gpio3_relay.py ".$zone_controler_child_id." ".$relay_status);```

**Comment by dvdcut** [comment]
i just did test on my raspberry pi 4 and it worked fine but are we changing gpio to bcm numbering? 
i m not sure if we can continue with WiringPi numbering as they dont match with bcn or with physical pin number. 

```root@pihome:~# gpio readall
 +-----+-----+---------+------+---+---Pi 2---+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 |     |     |    3.3v |      |   |  1 || 2  |   |      | 5v      |     |     |
 |   2 |   8 |   SDA.1 |   IN | 1 |  3 || 4  |   |      | 5v      |     |     |
 |   3 |   9 |   SCL.1 |   IN | 1 |  5 || 6  |   |      | 0v      |     |     |
 |   4 |   7 | GPIO. 7 |   IN | 1 |  7 || 8  | 1 | ALT0 | TxD     | 15  | 14  |
 |     |     |      0v |      |   |  9 || 10 | 1 | ALT0 | RxD     | 16  | 15  |
 |  17 |   0 | GPIO. 0 |   IN | 0 | 11 || 12 | 0 | IN   | GPIO. 1 | 1   | 18  |
 |  27 |   2 | GPIO. 2 |   IN | 0 | 13 || 14 |   |      | 0v      |     |     |
 |  22 |   3 | GPIO. 3 |   IN | 0 | 15 || 16 | 0 | IN   | GPIO. 4 | 4   | 23  |
 |     |     |    3.3v |      |   | 17 || 18 | 0 | IN   | GPIO. 5 | 5   | 24  |
 |  10 |  12 |    MOSI |   IN | 0 | 19 || 20 |   |      | 0v      |     |     |
 |   9 |  13 |    MISO |   IN | 0 | 21 || 22 | 0 | IN   | GPIO. 6 | 6   | 25  |
 |  11 |  14 |    SCLK |   IN | 0 | 23 || 24 | 1 | IN   | CE0     | 10  | 8   |
 |     |     |      0v |      |   | 25 || 26 | 1 | IN   | CE1     | 11  | 7   |
 |   0 |  30 |   SDA.0 |   IN | 1 | 27 || 28 | 1 | IN   | SCL.0   | 31  | 1   |
 |   5 |  21 | GPIO.21 |  OUT | 1 | 29 || 30 |   |      | 0v      |     |     |
 |   6 |  22 | GPIO.22 |  OUT | 1 | 31 || 32 | 0 | IN   | GPIO.26 | 26  | 12  |
 |  13 |  23 | GPIO.23 |  OUT | 1 | 33 || 34 |   |      | 0v      |     |     |
 |  19 |  24 | GPIO.24 |  OUT | 1 | 35 || 36 | 0 | IN   | GPIO.27 | 27  | 16  |
 |  26 |  25 | GPIO.25 |   IN | 0 | 37 || 38 | 0 | IN   | GPIO.28 | 28  | 20  |
 |     |     |      0v |      |   | 39 || 40 | 0 | IN   | GPIO.29 | 29  | 21  |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+---Pi 2---+---+------+---------+-----+-----+
```

**Comment by twa127** [comment]
we could map the pins in the python module if we wanted to keep the database the same, not an issue for me using beaglebone as I never used WiringPi

**Comment by dvdcut** [comment]
may be sticking with wiringpi pin numbering is bad idea, i suggest to stay move to BCN or physical pin numbering. my vote would be for physical pin numbering easy and no confusion.

**Comment by pihome-shc** [comment]
@twa127 how much effort it requires to map those pins to physical or bcm pin numbering, actually what is the default number in that library?

**Comment by twa127** [comment]
the default number is the BCM pin num eg 'gpio3_relay.py 23 1' would set GPIO23 (physical header pin 16). Mapping to WiringPi would not be difficult

**Comment by pihome-shc** [comment]
Now time to decide which way we want to go:
### Physical PIN number 
### Wiringpi PIN number 
### BCM PIN number 

Physical PIN number would be easy to visually map them. 

Staying with wiringpi Numbers means all existing installation can function without any change. 

BCM is good option and I assume people with rpi know what they are doing 🤔but not easy to visually map them. 

I would prefer to go with physical PIN numbering but @twa127 you are going to work on this so it’s your call.

**Comment by twa127** [comment]
Physical pin numbering is slightly better for me as this is basically how the beaglebone works (except it has two 46 pin headers, rather than the RPi's one 40 pin header).

So my vote is Physical

**Comment by dvdcut** [comment]
i have tested this on my rpi 4 and physical pin working great,

**Comment by pihome-shc** [comment]
@twa127 i did testing last night and it worked as expected, can you do pull request for this please.

**Comment by twa127** [comment]
Is it okay if I add pin mapping for my beaglebone as well, this way I don't have to maintain a separate version?

**Comment by pihome-shc** [comment]
I don’t see any problem with that, but users get to select rpi or beaglebone or how it will work when selecting PIN number ?

**Comment by twa127** [comment]
I'll detect the board type in the python eg 
import platform
system_name = platform.node()
if system_name == "beaglebone" :
    bb pin dict
else:
    rpi pin dict

**Comment by pihome-shc** [comment]
That would be great, do you need me to do some testing?

**Comment by twa127** [comment]
Great I’ll code it and send

**Comment by twa127** [comment]
Can you test please, the RPi code has not changed from the last time, just tested for board_id and then build pin directory depending on board type -

[gpio3_relay.zip](https://github.com/pihome-shc/pihome/files/4569850/gpio3_relay.zip)

**Comment by dvdcut** [comment]
it is working, i didnt connect relay to my rpi, 


```
root@pihome:~# python3 /var/www/cron/gpio/gpio3_relay.py 37 1

  _____    _   _    _
 |  __ \  (_) | |  | |
 | |__) |  _  | |__| |   ___    _ __ ___     ___
 |  ___/  | | |  __  |  / _ \  | |_  \_ \   / _ \
 | |      | | | |  | | | (_) | | | | | | | |  __/
 |_|      |_| |_|  |_|  \___/  |_| |_| |_|  \___|

    S M A R T   H E A T I N G   C O N T R O L

********************************************************
*   GPIO Interface Relay Support Communication Script  *
*    Build Date: 25/04/2020 Version 0.01               *
*    Last Modified: 25/04/2020                         *
*                                 Have Fun - PiHome.eu *
********************************************************

Pin Number  D26
HIGH
root@pihome:~#

```

**Comment by pihome-shc** [comment]
@twa127 
great work, i tested this on raspberry pi 4. can you do pull request now please. and i have to update documentation for this so users know about this update.

**Comment by pihome-shc** [comment]
I think it requires changes to add zone to show user about PIN numbering,

**Comment by twa127** [comment]
updated en.php to reflect change

**Comment by pihome-shc** [comment]
@twa127 / @dvdcut  is there anything more needed in this issue?

**Comment by twa127** [comment]
No I think it’s all sorted

**Comment by dvdcut** [comment]
Yes all sorted, @twa127 Thank you for your help.
