### ISSUE TITLE
Add-On: Electrical Immersion Control 

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/pihome#221]
As the title says: now code is much simplified and i think its time to offer some add-ons and i think first to have this add-on would be Electrical Immersion Control for hot water. 
how can this co-exit with other heating system in pihome is up for discussion.

**Comment by twa127** [comment]
now that's going to need a big relay :-)

**Comment by dvdcut** [comment]
yes, it does, but its lot cheaper and safe then i initially thought, i bought one from my local electrical shop and it was 15euro for GE brand, 
but what do you think of Add-On(s) offer other things, Electrical Immersion is just one example.

**Comment by pihome-shc** [comment]
i have received truck load of emails for add-ons i.e light bulb, extractor fan, you name it and having Electrical Immersion Control would be great thing as it is related to heating control, again how would we add it to exiting system? does it needs to be in schedule as independent zone?

**Comment by twa127** [comment]
I would have thought immersion as just another zone and schedule as required.

I'm playing with a light switch at the moment, can't decide if it fits in to PiHome GUI or should be something else :-)

**Comment by pihome-shc** [comment]
no it can not be and it shouldn't trigger gas boiler either, may be zone but zone without boiler.

**Comment by dvdcut** [comment]
@pihome-shc is right Electrical Immersion can not be treated as zone and it should not trigger boiler either, that is why it would be Add-On. 

for any other add-on we need to setup something in system to treat these add-ons each individual entity or item or we could make them part of each zone and on main page when you click any zone icon it brings different options for that zone with heating schedules.

**Comment by harvybob** [comment]
Im just thinking about this - my i2c setup does not trigger the boiler - it just opens the zone valve... surely this can be applied in the same way to the Immersion heater?

**Comment by dvdcut** [comment]
@harvybob but i have boiler connected as normal way, adding Electrical Immersion as zone then when ever there is trigger for Immersion it will send on command to boiler. 
have look at [boiler.php](https://github.com/pihome-shc/pihome/blob/a9cfb206381216ac057192ff68669e52b51b9412/cron/boiler.php#L483) and you can see it search in zone array if any zone is on it set boiler to on.

**Comment by harvybob** [comment]
@dvdcut  if you have two boilers one has the trigger to actually fire, the second has no trigger - how does boiler.php handle that? (my version is 1.64 so may be out of date!)

**Comment by dvdcut** [comment]
i dont think there is option for second boiler in boiler.php

**Comment by harvybob** [comment]
> i dont think there is option for second boiler in boiler.php

would this be a potential easy way to have two sets of "zones" where one is heating related - ie invokes the boiler relay, and a second is the non boiler related - lights,  cat flaps etc etc

**Comment by dvdcut** [comment]
Yes, something like that, but another option would be to reference these extra add-on to each zone, child of a zone

**Comment by dvdcut** [comment]
i think this Electrical Immersion Control act as zone but independent and can not call for heat from boiler and how to achieve this is simple then i thought. 
Some modicication is needed on Add Zone section with some java/ajax so if user select Zone type Electrical Immersion then it hid boiler field. 

**boiler.php**
[add on Line 172 	](https://github.com/pihome-shc/pihome/blob/1b887a019e1d411b909617de695976a31851fe3c/cron/boiler.php#L172)
`$zone_type=$row['type'];`

then at around [line 466](https://github.com/pihome-shc/pihome/blob/1b887a019e1d411b909617de695976a31851fe3c/cron/boiler.php#L464) make these changes. 
```
if ($zone_type != 'Heating' OR $zone_type != 'Water'){
	//all zone status to boiler array and increment array index
	$boiler[$boiler_index] = $zone_status;
	$boiler_index = $boiler_index+1;
	//all zone ids and status to multidimensional Array. and increment array index.
	$zone_log[$zone_index] = (array('zone_id' =>$zone_id, 'status'=>$zone_status));
	$zone_index = $zone_index+1;
}
```

**Comment by pihome-shc** [comment]
@dvdcut good thinking, i tested this change with my live system and it worked ok, now need to test this with dummy immersion zone also creating it as zone automatically gives option to have it in schedule so user can schedule electrical immersion. 

One small issue though: the way zone is created it refer to boiler in its record, i know that record isnt used anywhere, may be time to remove that record as well.

**Comment by pihome-shc** [comment]
you have added options in graph for immersion but it is not going to make any difference as zone and boiler logs are recorded after boiler is triggered.

**Comment by pihome-shc** [comment]
zone.php need some modification for immersion option

**Comment by dvdcut** [comment]
yes, i realize that as well after modifying chartfooter.php may be in future some one can suggest better way or recording zone records. 

i made some changes in zone.php with following addition to zone type as Immersion in zone table. 
`<option><?php echo $lang['zone_type_electrical_immersion']; ?></option>`

**Comment by pihome-shc** [comment]
any further update or discussion required on this?

**Comment by dvdcut** [comment]
i think no further discussion required for Electrical immersion controller, i'll open another issue for general discussion for other Add-On. like @twa127 experimenting with light switch i m thinking to implement kitchen exhaust fan. i'll this to @pihome-shc to close this issue you are happy.

**Comment by pihome-shc** [comment]
closing issue
