### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by twa127** [pihome-shc/pihome#222]
Do you think we should consider migrating to the latest version of python?

**Comment by pihome-shc** [comment]
Up until now single image is compatible with all versions of rpi, do you think moving to altes version of python will make single image compatible across all rpi models?

**Comment by pihome-shc** [comment]
i have rpi 3, 4 and zoro w, if you need testing i can do this for you no problem,

**Comment by twa127** [comment]
can't see why not Raspian comes with Python 2 & 3, only reason for asking is that 2 is now obsolete

**Comment by pihome-shc** [comment]
then i dont see any problem updating to version 3

**Comment by twa127** [comment]
oh dear I need to upskill then :-)))

**Comment by pihome-shc** [comment]
You asked for it :)

**Comment by dvdcut** [comment]
python isnt major part of pihome i think only place python is used is gateway or i2c relay.

**Comment by harvybob** [comment]
I packed away my test pi, but i will set it up tonight and test i2c with python3 - i ran the upgrade utility and the only changes made were the comments so fingers crossed with that side!

**Comment by pihome-shc** [comment]
@harvybob, 
did you mange you test your 12c relay with python version 3?

**Comment by harvybob** [comment]
both easyi2c.py and i2c_relay.py (both needed together) work on python 3.5

**Comment by pihome-shc** [comment]
Free python 3 course if anyone interested, don’t know how good is this one. 

https://www.udemy.com/course/python-3-bootcamp-2020/?couponCode=PYTHON-LEARN

**Comment by twa127** [comment]
Here is the updated python3 gateway code, I've been running it on both a serial and ethernet gateway for over 24 hours, please let me know what you think

[cron.zip](https://github.com/pihome-shc/pihome/files/4616551/cron.zip)

**Comment by dvdcut** [comment]
Notes to Python3 as @twa127 mentioned in other issue: 
Check version of pthon you have: 
`python --version`
Set python 3 as default: 
`nano ~/.bashrc`
Add the following after the last line in the file
`alias python='/usr/bin/python3'`
To implement the change: 
`source ~/.bashrc`

Remember that after this if you want to run python 2 code you will have to call as phython2 e.g python2 /var/www/cron/gateway.py (to run the existing gateway script)
Also you need to install phthon3 mysql library 
`sudo apt-get install python3-mysqldb`

**Comment by dvdcut** [comment]
@twa127, 
dont know what is wrong but find_mygw3.py isnt finding my gateway, i deliberately changed ip to wrong one in my database for gateway and killed exiting process to let check_gw3.php find gateway but after over one hour still not found. but then i run old scrip `python2 /var/www/cron/find_mygw/find_mygw.py` and in few minuts it found gateway. dont know what is wrong with find_mygw3.py

**Comment by twa127** [comment]
okay I'll have a look, it uses an updated version of ping.py, so maybe it's something related to that

**Comment by twa127** [comment]
I did not notice that ping.py had been doctored to return when the ip/port was discovered. Implemented the same process for ping3.py, so should now find the gateway

[ping3 .zip](https://github.com/pihome-shc/pihome/files/4617647/ping3.zip)

**Comment by pihome-shc** [comment]
@twa127  / @dvdcut great work, i just tested and it is working for me with your latest ping3.py, 
also steps for setting python3 as default worked as well.

**Comment by twa127** [comment]
good news, so most of the python now works with version 3, I'll mop up the rest

do you want to stick with the '3' in the file names or should be drop it?

**Comment by pihome-shc** [comment]
i lets move to python 3 and keep old name (remove 3 from the name)

**Comment by pihome-shc** [comment]
@harvybob can you test your i2c relay with python 3

**Comment by twa127** [comment]
I think we could do i2c using 'blinka' but I don't have an i2c relay to play with. I've moved my boiler watchdog display over to blinka using SPI, did have a few problems but they were down to the beaglebone kernel naming conventions tor the SPI ports
![case](https://user-images.githubusercontent.com/46624596/81739319-0ac4e280-9493-11ea-92e4-b13543fb8e99.JPG)

**Comment by pihome-shc** [comment]
@twa127 that display looks great, i also monitor my flow temperature. but not return temperature, did you put any intelligence based on flow and return temperature? 

to test i2c @harvybob is the only one who have i2c relay board.

**Comment by twa127** [comment]
Nope the main function is to monitor the fault condition and attempt to reset the boiler x times to clear the fault. The main fault condition is due to the return temp not tracking the flow temp in a given time, so the boiler thinks there is a blockage, hence I display both and the boiler has flow and return thermistors which return current temps

**Comment by harvybob** [comment]
> @harvybob can you test your i2c relay with python 3

Mine work fine - do you want me to push the new code? tbh the only code that needed changing was the comments put in for PiHome!

(i have not done a full pull of the new code - just tested the i2c relay board itself!)

**Comment by harvybob** [comment]
> @twa127 / @dvdcut great work, i just tested and it is working for me with your latest ping3.py,
also steps for setting python3 as default worked as well.

Just a thought, the change to 3 using profile may not work when running cron jobs? (a good few years back when i was working on RHEL 5 we had problems where changes in the profile didnt work in the script. As part of crontab or the job itself we had to invoke the profile...

**Comment by twa127** [comment]
Morning

We execute call gpio_ds18b20.py and notice.py as cron jobs, the rest are called from within php code.

We could execute as, for instance , python3 gpio_ds18b20.py then no need to make python 3 the default.

I don't think the pycache folder gets created in every instance, for example running gpio_ds18b20.py or notice.py does not create a pycache folder, but find_mygw does, but in fact this is little different to the current python2 find_mygw which produces a ping.pyc file rather than the  __pycache__ folder produced by the python3 version

I

**Comment by twa127** [comment]
"When you import a module, Python stores the compiled bytecode in that directory so that future imports can use it directly, rather than having to parse and compile the source again. It does not do that for merely running a script, only when a file is imported. (Previous versions used to store the cached bytecode as .pyc files that littered up the same directory as the .py files, but starting in Python 3 they were moved to a subdirectory to make things tidier.)"

In the case if find_mygw.py ping is imported and for i2c_relay.py  easyi2c is imported and this is where the .pyc file or  __pycache__ directory get created.

**Comment by harvybob** [comment]
Personally i think doing this
` python3 gpio_ds18b20.py `

would be a better way - a bit more work  but it will mean if other people dont make 3 the default etc then it wont cause problems ,plus at some point when 4 comes round and we migrate to 4, we will know which ones are 3 and 4 etc.

The pycache is just to keep github tidy! as soon as someone runs the code it will get created anyway, but github doesnt need the cache'd files does it?

**Comment by twa127** [comment]
we have already sent a precedent in boiler.php by executing the new gpio relay code with python3, so it gets my vote :-)

I don't see the need to distribute the pycache directories as they get created at run time, where required.

**Comment by dvdcut** [comment]
i can see in boiler.php  both ways its not unified, 

`exec("python3 /var/www/cron/gpio/gpio3_relay.py " .$boiler_node_child_id ." ".$relay_on );`
and 
`exec("python /var/www/cron/i2c/i2c_relay.py" .$boiler_node_id." ".$boiler_node_child_id." 1"); `

i m based on pihome img file so all the hard work will be done for me by author :)

**Comment by twa127** [comment]
Hi,

Yes that's because we have already deployed the python3 gpio relay code, but not yet deployed the i2c update to python3

**Comment by harvybob** [comment]
I've pushed #231  to add two new files for the i2c relays. Boiler.php has NOT been updated - i need to rebuild my setup with the current code - I have a VM where my main code runs, along with the database, and then a PI which does the DS and actual relays... need to rebuild both but need to do a full rebuild for db which will take time.

**Comment by twa127** [comment]
can someone give this a try please, you need to execute with python3 gpio_ds18b20.py

[gpio_ds18b20.zip](https://github.com/pihome-shc/pihome/files/4621698/gpio_ds18b20.zip)

**Comment by dvdcut** [comment]
@twa127 i tested this and it worked for me, i even deleted my exiting ds sensors from database to check it if creates them again or not, and that worked as well.

**Comment by twa127** [comment]
great, the changes were only cosmetic

**Comment by pihome-shc** [comment]
@dvdcut thank you for testing this, @twa127 can you do pull request for ds18b20 sensors please. i m planing to another release over weekend and want to get added in next version.

**Comment by twa127** [comment]
Okay, I'll do all the python3 updates using existing naming (ie no 3)

**Comment by harvybob** [comment]
updated boiler.php to refer to python3 #235 for the i2c control.

**Comment by pihome-shc** [comment]
@twa127 
i m getting this error while starting gateway.py file 

root@pihome:/var/www# python3 --version
Python 3.7.3
root@pihome:/var/www#


```
EOFError: telnet connection closed
More info in log file: /var/www/logs/main.log
Traceback (most recent call last):
  File "/var/www/cron/gateway.py", line 354, in <module>
    logging.exception(e)
NameError: name 'e' is not defined
```

**Comment by pihome-shc** [comment]
@twa127 please ignore my last message. it was my gateway.

**Comment by twa127** [comment]
no problem, I've got something else for you to test :-))

The attached is an up to date python3 version of fauxmo, it works with my version1 echo, can you please give it a try with a newer echo. You need to edit the config.json file and add a zonename for your setup (any active zone will do for the test) then start with fauxmo -vv

Echo should be able to discover a new 'Test Switch', which should control the zone you selected. Note: use %20 for any white spaces in the zone name.

If it works I'll replace the existing echo setup

**Comment by pihome-shc** [comment]
@twa127 after running install script and 

```
root@pihome:/var/www/add_on/amazon_echo# systemctl status  pihome_amazon_echo.service
● pihome_amazon_echo.service - Echo
   Loaded: loaded (/lib/systemd/system/pihome_amazon_echo.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-05-13 22:53:59 BST; 34s ago
  Process: 18101 ExecStart=/usr/bin/python -u /var/www/add_on/amazon_echo/echo_pihome.py (code=exited, status=1/FAILURE)
 Main PID: 18101 (code=exited, status=1/FAILURE)

May 13 22:53:59 pihome systemd[1]: Started Echo.
May 13 22:53:59 pihome python[18101]: Traceback (most recent call last):
May 13 22:53:59 pihome python[18101]:   File "/var/www/add_on/amazon_echo/echo_pihome.py", line 15, in <module>
May 13 22:53:59 pihome python[18101]:     import fauxmo
May 13 22:53:59 pihome python[18101]:   File "/var/www/add_on/amazon_echo/fauxmo.py", line 27
May 13 22:53:59 pihome python[18101]:     def main(config_path_str: str = None, verbosity: int = 20) -> None:
May 13 22:53:59 pihome python[18101]:                             ^
May 13 22:53:59 pihome python[18101]: SyntaxError: invalid syntax
May 13 22:53:59 pihome systemd[1]: pihome_amazon_echo.service: Main process exited, code=exited, status=1/FAILURE
May 13 22:53:59 pihome systemd[1]: pihome_amazon_echo.service: Failed with result 'exit-code'.
root@pihome:/var/www/add_on/amazon_echo#
```


if i run 
```
root@pihome:/var/www/add_on/amazon_echo# python fauxmo.py -vv
Traceback (most recent call last):
  File "fauxmo.py", line 16, in <module>
    from fauxmo import __version__, logger
  File "/var/www/add_on/amazon_echo/fauxmo.py", line 16, in <module>
    from fauxmo import __version__, logger
ImportError: cannot import name '__version__' from 'fauxmo' (/var/www/add_on/amazon_echo/fauxmo.py)
root@pihome:/var/www/add_on/amazon_echo#
```

**Comment by twa127** [comment]
Very sorry I did not really make myself plain. This version of fauxmo is very different from the python2 one we are currently using, to test we do not need to use any of the existing installation process. The advantage to this one is that it is maintained, see https://github.com/n8henrie/fauxmo

To test:

1. Install faxmon with - pip3 install fauxmo
2. create config directory with - mkdir /etc/fauxmo
3. copy the config.json file I sent before with - cp config.json /etc/fauxmon
4. edit /etc/fauxmon/config.json and change the zonename to match your setup (using %20 for any white spaces)
5. start with verbose debugging using - fauxmon -vv  
6. echo should be able to discover the new Test Switch

**Comment by pihome-shc** [comment]
@twa127 
i tested echo without modifying anything and it worked, can we produce zone names automatically? 

```
root@pihome:~# fauxmo -vv
2020-05-14 14:35:50 fauxmo:42       INFO     Fauxmo v0.5.0
2020-05-14 14:35:50 fauxmo:51       INFO     Using config: /etc/fauxmo/config.json
2020-05-14 14:35:50 fauxmo:136      INFO     Starting UDP server
2020-05-14 14:35:57 fauxmo:57       INFO     setup.xml requested by Echo
2020-05-14 14:35:57 fauxmo:66       INFO     request BasicEvent1
2020-05-14 14:35:57 fauxmo:140      INFO     Attempting to get state for Test Switch
2020-05-14 14:35:57 fauxmo:146      INFO     Test Switch state: off
2020-05-14 14:35:59 fauxmo:66       INFO     request BasicEvent1
2020-05-14 14:35:59 fauxmo:140      INFO     Attempting to get state for Test Switch
2020-05-14 14:35:59 fauxmo:146      INFO     Test Switch state: off
2020-05-14 14:36:13 fauxmo:57       INFO     setup.xml requested by Echo
2020-05-14 14:36:53 fauxmo:66       INFO     request BasicEvent1
2020-05-14 14:36:53 fauxmo:162      INFO     Attempting to turn on Test Switch
2020-05-14 14:36:53 fauxmo:66       INFO     request BasicEvent1
2020-05-14 14:36:53 fauxmo:140      INFO     Attempting to get state for Test Switch
2020-05-14 14:36:53 fauxmo:146      INFO     Test Switch state: on
2020-05-14 14:37:11 fauxmo:57       INFO     setup.xml requested by Echo
2020-05-14 14:37:11 fauxmo:66       INFO     request BasicEvent1
2020-05-14 14:37:11 fauxmo:157      INFO     Attempting to turn off Test Switch
2020-05-14 14:37:11 fauxmo:66       INFO     request BasicEvent1
2020-05-14 14:37:11 fauxmo:140      INFO     Attempting to get state for Test Switch
2020-05-14 14:37:11 fauxmo:146      INFO     Test Switch state: off
```

**Comment by twa127** [comment]
Hi,

That's good news, I'll come up with an install.sh to install, modify the service and build the config.json similar to the homekit solution and commit when ready

**Comment by pihome-shc** [comment]
@twa127,
Thank you for your hard work.

**Comment by harvybob** [comment]
Just noticed a typo in boiler.php with reference to i2c_relay.py pushing the fix - to add a space after the .py

Only affects i2c

**Comment by pihome-shc** [comment]
@twa127 Any more work needed for python 3 or can this issue be closed?

**Comment by twa127** [comment]
Hi

I think it’s safe to close
