### ISSUE TITLE
Gateway script with wired and wireless ds18b20 

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/pihome#224]
This looks some bug in the gateway.py script, 
background:
i added two wired sensors to raspberry pi and enable cron job for ds18b20 sensors and it worked ok as expected. 
when i power on wireless sensors gateway.py script keep terminating and i think it is related to node id of wired sensors node_id. 
**one example of error:**
```
Size of the String Received:  41
Date & Time:                  Wed Apr 29 15:32:32 2020
Full String Received:         32;255;0;0;17;2.3.1\n
Full Statement Received:      ['32', '255', '0', '0', '17', '2.3.1\n']
Node ID:                      32
Child Sensor ID:              255
Message Type:                 0
Acknowledge:                  0
Sub Type:                     17
Pay Load:                     2.3.1
/var/www/cron/gateway.py:182: Warning: (1292L, "Truncated incorrect DOUBLE value: '28-03156520b4ff                                                                                     '")
  cur.execute('SELECT COUNT(*) FROM `nodes` where node_id = (%s)', (node_id, ))
/var/www/cron/gateway.py:182: Warning: (1292L, "Truncated incorrect DOUBLE value: '28-01156572dbff                                                                                     '")
  cur.execute('SELECT COUNT(*) FROM `nodes` where node_id = (%s)', (node_id, ))
1: Node ID: 32  Already Exist In Node Table, Updating MS Version
DB Error 1292: Truncated incorrect DOUBLE value: '28-03156520b4ff                                                                                     '
More info in log file: /var/www/logs/main.log
### 2020-04-29 15:32:32,225 - ERROR ###
Traceback (most recent call last):
  File "/var/www/cron/gateway.py", line 194, in <module>
    cur.execute('UPDATE nodes SET ms_version = %s where node_id = %s', (payload, node_id))
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
OperationalError: (1292, "Truncated incorrect DOUBLE value: '28-03156520b4ff    
```

i have warped node_id with single ' after many tries i got it working but now it is presenting 3 more problems, 
i. it does not update sensor name 
ii. it does not update sketch version
iii. each time i reset sensor it create new entry in node table again without name and sketch version. 

on screen it present all ok but db update not happening. i can not fix this issue. see attached gateway.zip file, may be there is better way to address this. 

can any one looks at this please. 
[gateway.zip](https://github.com/pihome-shc/pihome/files/4552494/gateway.zip)

**Comment by twa127** [comment]
node_id is an integer and the node_id column is CHAR, so hence the error, you could try replacing line 182 with -

        query = 'SELECT COUNT(*) FROM `nodes` where node_id = ' + str(node_id)
        cur.execute(query)

**Comment by twa127** [comment]
Only happens when you have ds18b20 sensors nodes in the table

**Comment by dvdcut** [comment]
i installed wired sensors on my raspberry pi to monitor spare room temperature. if that is question then yes it only happened since in installed wired sensor. 
this time after resting sensors few times it didnt create multiple entries for same sensors but still name and sketch version is missing. 

```
Size of the String Received:  41
Date & Time:                  Wed Apr 29 22:31:19 2020
Full String Received:         32;255;0;0;17;2.3.1\n
Full Statement Received:      ['32', '255', '0', '0', '17', '2.3.1\n']
Node ID:                      32
Child Sensor ID:              255
Message Type:                 0
Acknowledge:                  0
Sub Type:                     17
Pay Load:                     2.3.1
/var/www/cron/gateway.py:184: Warning: (1292L, "Truncated incorrect DOUBLE value: '28-03156520b4ff                                                                                     '")
  cur.execute(query)
/var/www/cron/gateway.py:184: Warning: (1292L, "Truncated incorrect DOUBLE value: '28-01156572dbff                                                                                     '")
  cur.execute(query)
1: Adding Node ID: 32 MySensors Version: 2.3.1

```
Here are the changes. 
```
				# ..::Step One::..
				# First time Temperature Sensors Node Comes online: Add Node to The Nodes Table.
				if (node_id != 0 and child_sensor_id == 255 and message_type == 0 and sub_type == 17):
				#if (child_sensor_id != 255 and message_type == 0):
					#cur.execute('SELECT COUNT(*) FROM `nodes` where node_id = (%s)', ('node_id', )) 
					query = 'SELECT COUNT(*) FROM `nodes` where node_id = ' + str(node_id)
					cur.execute(query)
					row = cur.fetchone()  
					row = int(row[0])
					if (row == 0):
```

**Comment by twa127** [comment]
yeah I'm sure you have identified a bug in gateway.py script, I can reproduce by creating a dummy ds18b20 node, I'll try adding a wireless node and see what happens

**Comment by twa127** [comment]
quick test - added a single mysensor node with no name or sketch_version

**Comment by dvdcut** [comment]
yes i did :( but what is the fix for this, you have better control over python

**Comment by twa127** [comment]
Good Morning

please try this

[gateway.zip](https://github.com/pihome-shc/pihome/files/4556737/gateway.zip)

**Comment by dvdcut** [comment]
just like that, waoo, that is great and it worked, i haven't restarted any other nodes, do you think it will be ok for other wireless nodes ? 
```
node_id = str(statement[0])
```

**Comment by twa127** [comment]
Glad it worked okay, yeah should be okay for the wireless nodes, I deleted one and it came back okay.

Do you think we should have a new 'type' for these ds18b20 sensors, as calling them GPIO means they show up in the nodes settings gui?

**Comment by twa127** [comment]
We could call them GPIOSensor

**Comment by dvdcut** [comment]
i didnt notice they show up in nodes, but not you got me thinking should we rename nodes to wired node, Yes GPIOSensors is good option

**Comment by twa127** [comment]
yep would only then need a little tweak in model.php
change $query = "SELECT * FROM nodes where type != 'MySensor';";
to $query = "SELECT * FROM nodes where type not like '%Sensor';";

**Comment by pihome-shc** [comment]
@twa127/ @dvdcut i did test and pull request worked great, anything else you need or can this issue be closed ?

**Comment by twa127** [comment]
Okay for me

**Comment by dvdcut** [comment]
@twa127 thank you for fixing this. i will close this issue now,
