### ISSUE TITLE
python error for physical gpio

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/pihome#227]
i think space is missing and small other things. 
```
2020-05-08 11:09:25 - Zone: Sensor Reading     29.80
2020-05-08 11:09:25 - Zone: Weather Factor     0.6
2020-05-08 11:09:25 - Zone: DeadBand           0.5
2020-05-08 11:09:25 - Zone: Temperature        30.9
2020-05-08 11:09:25 - Zone ID: 35
2020-05-08 11:09:25 - Zone: Hot Water Controller: 0 Controller Child: 33 Zone Status: 0
2020-05-08 11:09:25 - Zone: Hot Water Stop Cause: No Schedule - Target C:0 Zone C:30.4
2020-05-08 11:09:25 - Zone: GIOP Relay Status: 1 (0=On, 1=Off)
----------------------------------------------------------------------------------------
2020-05-08 11:09:25 - Boiler Switched Off At: 2020-05-08 07:44:02
python3: can't open file '/var/www/cron/gpio/gpio3_relay.py35': [Errno 2] No such file or directory
2020-05-08 11:09:25 - Boiler GIOP: 35 Status: 1 (0=On, 1=Off)
2020-05-08 11:09:25 - Boiler Fired Status: 0
2020-05-08 11:09:25 - Boiler Hysteresis Status: 0
----------------------------------------------------------------------------------------
2020-05-08 11:09:25 - Boiler Script Ended

```

**Comment by pihome-shc** [comment]
@dvdcut i had comments on PiHome website yesterday [Shaun Jepson](http://www.pihome.eu/2020/04/11/pihome-version-1-74/#comment-21325) had same issue, i thought he needed following dependencies installed. (i replied without ready :( )

```
sudo apt install python3-pip
sudo pip3 install RPI.GPIO
sudo pip3 install adafruit-blinka
```

**Comment by pihome-shc** [comment]
@dvdcut any further testing needed? @twa127 you are the expert on python. anything else needed for this issue?

**Comment by twa127** [comment]
I think we are okay with the gpio code, just need to make sure the dependences are installed, also need to add to the list - 
sudo apt-get install python3-mysqldb

#222 need this one for the gateway code migration to python3. I've moved it across to python3 can you please test the attached gateway migration - the main change was to the serial read/write as python3 handles strings differently, I've included '3' in the filenames just to distinguish it from the old version, you will need to change the cron job from check_gw.php to  check_gw3.php and kill gateway.py if it's still running.

[cron.zip](https://github.com/pihome-shc/pihome/files/4614042/cron.zip)

**Comment by dvdcut** [comment]
@twa127 
i tried your code. 
```
root@pihome:~# python /var/www/cron/gateway3.py
  File "/var/www/cron/gateway3.py", line 162
    print("Full String Received:         ",end = in_str)
                                               ^
SyntaxError: invalid syntax
```

**Comment by twa127** [comment]
are you running under python3 by default, if not needs to be

python3 /var/www/cron/gateway3.py

**Comment by dvdcut** [comment]
my mistake, how i can make python3 as default?
by running python3 /var/www/cron/gateway3.py it is working.

**Comment by twa127** [comment]
you can check what is the current version by using python --version

to set python 3 as default - nano ~/.bashrc and at the following after the last line in the file

alias python='/usr/bin/python3'

remember that after this if you want to run python 2 code you will have to call as phython2 eg
 python2 /var/www/cron/gateway.py (to run the existing gateway script)

**Comment by twa127** [comment]
I've been running both a serial and ethernet gateway with the python3 code for the last 24hours and so far no problems

**Comment by dvdcut** [comment]
root@pihome:~# python --version
Python 2.7.16
root@pihome:~#

**Comment by dvdcut** [comment]
```
root@pihome: ~ # python3 --version
Python 3.7.3
root@pihome:~#
```

**Comment by dvdcut** [comment]
ok, its all looks ok, we have to make python 3 as default or call it with python3 
one question inside check_gw3.php 
you changed this 
```
//if status set to 0 then check if gateway PID is running and if found then kill
if ($gw_status == '0') {
	//Gateway Python Script location
	$gw_script_txt = 'python /var/www/cron/gateway.py';
	//Check if Porocess is running and get its PID
	exec("ps aux | grep '$gw_script_txt' | grep -v grep | awk '{ print $2 }' | head -1", $out);
	if (count($out) > 1) {
		echo "\033[36m".date('Y-m-d H:i:s')."\033[0m - Gateway PID is: \033[41m".$out[0]."\033[0m \n";
		echo "\033[36m".date('Y-m-d H:i:s')."\033[0m - Stopping Python Gateway Script \n";
		//Kill Gateway Python Scrip PID
		exec("kill -9 '$out[0]'");
	} else {
		echo "\033[36m".date('Y-m-d H:i:s'). "\033[0m - Gateway is DISABLED \n";
	}
```
to this 

```
//if status set to 0 then check if gateway PID is running and if found then kill
if ($gw_status == '0') {
	exec("ps -p $gw_pid", $output);
        if (count($output) > 1) {
	        echo "\033[36m".date('Y-m-d H:i:s'). "\033[0m - Stopping Python Gateway Script \n";
        	exec("kill -9 $gw_pid");
		echo $line;
        } else {
		echo "\033[36m".date('Y-m-d H:i:s'). "\033[0m - Python Gateway Script is DISABLED \n";
	}
```

**Comment by twa127** [comment]
sorry I was not using the latest copy of check_gw, the only changes were to the python calls, updated current version attached

[find_mygw3.zip](https://github.com/pihome-shc/pihome/files/4616342/find_mygw3.zip)

**Comment by dvdcut** [comment]
i was referring to check_gw3.php i didn't check find_mygw3.py

**Comment by twa127** [comment]
oops sorry sent the wrong file :-(

[check_gw3.zip](https://github.com/pihome-shc/pihome/files/4616454/check_gw3.zip)

**Comment by dvdcut** [comment]
can we close this issue and move this conversation to #222

**Comment by twa127** [comment]
sounds a good idea to me, I'll repost the code to test in that tread

**Comment by dvdcut** [comment]
closing this issue. now, gpio issue was resolved.
