### ISSUE TITLE
ds18b20 sensors as cron job

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/pihome#236]
receive this message on[ PiHome Website ](http://www.pihome.eu/2018/02/15/ds18b20-temperature-sensor-to-mysql-mariadb-database/#comment-25097)

I have a system with 3 wireless ds18b20 connected but also want to connect a wired ds18b20 to the pi
After initial problems I can now set up another zone using the wired ds18b20.  I couldn't see the new sensor so I enabled 1-wire in the pi configuration and then ran  
sudo python  /var/www/cron/gpio18b20.py (get errors if I don't use sudo)
I now have a new sensor and can create a new zone. So everything is working except for the Cron. I checked  /etc/crontab with crontab -e and there's nothing in it. 
I edited /etc/crontab and entered
*/1 * * * * python /var/www/cron/gpio_ds18b20.py &gt;/dev/null 2&gt;&amp;1
It didn't work so I changed it to
*/1 * * * * sudo python /var/www/cron/gpio_ds18b20.py &gt;/dev/null 2&gt;&amp;1
It still doesn't work
So I still don't know what to do. 
Any help would be gratefully received.

@twa127 any idea? i have same issue as well after moving to python 3

**Comment by twa127** [comment]
Hi now python3, RPi uses python2 by default, so unless you change the default, use

*/1 * * * * python3 /var/www/cron/gpio_ds18b20.py >/dev/null 2>&1

**Comment by pihome-shc** [comment]
after changing to python3 it is working for me. thank you.

**Comment by pihome-shc** [comment]
no further actions required.
