### ISSUE TITLE
Boost issue zone status not known (i2c?)

### ISSUE THREAD

**Issue by harvybob** [pihome-shc/pihome#240]
Hi Guys, I've updated to the latest software (the python 3 changes as of 15/5/20),
and have the following setup:

1) A VM running the database and the main code
2) A Pi2 B with DS18b20
3) A Pi1 B with two I2C relay Boards - IDs in the os as boards 32 and 33.

I created the nodes for the two relay boards - Type as I2C, Node ID as the board ID and number of children as 8.

I then went to add a Zone - the DS18B20 were already writing to the database so just a matter of selecting the correct relay board and relay, first issue: When i added the Nodes, it automatically creates the children as 1 to 8 - but my board needs 10-17. No matter - i manually changed the values on the Nodes table for the two boards to have a max child id of 17.

Then i go back to create the Node, and it needs a boilerID - now i dont have a boiler ID as my setup will be that the zone valve will activate the boiler?

I end up creating the boiler as my first I2C Node, and child 1 (note that i do not have a relay that will activate with the board id of 32, and relay id of 1!)

I've been testing various bits to make sure all is working and i've come across this error:
```----------------------------------------------------------------------------------------
2020-05-15 16:06:02 - Boost is Active for This Zone
2020-05-15 16:06:02 - Zone: Sensor Reading     24.06
2020-05-15 16:06:02 - Zone: Weather Factor     0.6
2020-05-15 16:06:02 - Zone: DeadBand           0.5
2020-05-15 16:06:02 - Zone: Temperature        25.16
2020-05-15 16:06:02 - Zone ID: 39
2020-05-15 16:06:02 - Zone: dining room Controller: 33 Controller Child: 16 Zone Status:
Traceback (most recent call last):
  File "/var/www/cron/i2c/i2c_relay.py", line 49, in <module>
    main()
  File "/var/www/cron/i2c/i2c_relay.py", line 40, in main
    status = int(sys.argv[3])
IndexError: list index out of range
2020-05-15 16:06:03 - Zone Relay Broad: 33 Relay No: 16 Status:
```

The error seen is because the Zone Status is not set - ie its not been populated. 

Another Zone which is working is:

```
----------------------------------------------------------------------------------------
2020-05-15 16:06:03 - Zone: Sensor Reading     24.56
2020-05-15 16:06:03 - Zone: Weather Factor     0.6
2020-05-15 16:06:03 - Zone: DeadBand           0.5
2020-05-15 16:06:03 - Zone: Temperature        25.66
2020-05-15 16:06:03 - Zone ID: 40
2020-05-15 16:06:03 - Zone: kitchen Controller: 33 Controller Child: 15 Zone Status: 0
2020-05-15 16:06:03 - Zone: kitchen Stop Cause: No Schedule - Target C:0 Zone C:25.16
2020-05-15 16:06:05 - Zone Relay Broad: 33 Relay No: 15 Status: 0
----------------------------------------------------------------------------------------
```

I seem to recall this issue appearing previously -but never got to the bottom of it - something to do with the boost i think and being close to the target values.

**Comment by pihome-shc** [comment]
when you i2c node, it ask for Number of Child Devices attached to Node, which gives max number of child devices number i.e if you add 10 it will give max number of child devices. but looks like its a bug where your child devices numbers are not starting from 1 to 10? 

On you boiler, even your boiler isnt controlled by PiHome you still need one boiler entry in database.

**Comment by harvybob** [comment]
> when you i2c node, it ask for Number of Child Devices attached to Node, which gives max number of child devices number i.e if you add 10 it will give max number of child devices. but looks like its a bug where your child devices numbers are not starting from 1 to 10?
> 
> On you boiler, even your boiler isnt controlled by PiHome you still need one boiler entry in database.

I had to do that as the way my i2c board is numbered is 10-17. The way the code is setup is that it uses the childId to select which relay to activate

**Comment by pihome-shc** [comment]
i think logic can be added for i2c child id as free text input,

**Comment by harvybob** [comment]
To be honest im ok with it working this way - i tell it its child id 1-17, i just use 10-17 so dont need to change on my account. The status thing is more the issue. Throws an error when boost is set, the zone does not get a correct status.

**Comment by pihome-shc** [comment]
@harvybob it looks like one one arrangement is passed to i2c python script, ie. status is blank
**2020-05-15 16:06:03 - Zone Relay Broad: 33 Relay No: 16 Status:**
i think best to change language for more clarity 

```
$lang['node_child_id'] = "Child Devices";
$lang['node_child_id_info'] = "Number of Attached Devices for i2c max number of child id";
```

**Comment by harvybob** [comment]
But ChildID 17 which is also active  works just fine, ,as does 16 when the temperature is lower then 24 degrees.

**Comment by pihome-shc** [comment]
@harvybob do we need to do anything further on this issue?

**Comment by harvybob** [comment]
Not sure - the error i guess is not having a status - which only happens when using boost..

**Comment by pihome-shc** [comment]
@harvybob it only happens when you boost one zone and rest of the zone stay normal? can you do some testing and run boiler.php and send all output.

**Comment by pihome-shc** [comment]
@harvybob can we close this issue? or any update?

**Comment by twa127** [comment]
Just for info - i2c_relay.py expects 3 parameters in order to drive the BV4627, the first is the i2c address of the board (default is 32 decimal, I guess if you had 2 boards, you would change the address of the second board to 33 decimal), the second parameter is the relay number of the board (1 to 8) and the final parameter is the relay state (0 = off, 1 = on). The code requires all 3 parameters in the correct sequence, note that the existing code does not check that it is passed all 3 arguments.

My understanding of using 2 BV4627 boards with the existing python script, is that each board would have its individual i2c address and 8 child ids numbered 1 to 8

**Comment by harvybob** [comment]
Hi twa127, The issue is that the status is unknown, not sure why but i cant get it to happen again at the moment (maybe because weather is hotter and already over the max set... 

I have the boards set with different id's etc and that is all working.

**Comment by pihome-shc** [comment]
@harvybob any further work required on this? can this issue be closed ?

**Comment by harvybob** [comment]
Not that i can identify, I cant seem to test/get the same error now so i cant really dig any more.
May as well close.
