### ISSUE TITLE
Battery voltage graph

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/pihome#244]
battery voltage and batter level graphs under the exiting graph. 

ps: i m already working on this o i will have it ready by tomorrow.

**Comment by pihome-shc** [comment]
i have 3 zone heating and temperature sensors only report battery if there is change in value, and db_cleanup.php removes values older then 3 months and after this i have 102197 records of battery records for past 3 months that is around 34,065 per temperature sensors. adding these many values to graph will make it very slow and specially on systems running on sd card or somehow  squeeze 102197 number into lot smaller that are workable.

**Comment by dvdcut** [comment]
following query gives me 25737 results (numbers are little lower then yours) 
```
SELECT * FROM nodes_battery WHERE node_id = 21;
```
after magic 😃 following query squeeze 25737 into 1301 records
```
SELECT bat_voltage, bat_level, `update`  FROM nodes_battery WHERE `update` >= last_day(now()) + interval 1 day - interval 3 MONTH 
AND bat_level is not NULL and node_id = '21' GROUP BY YEAR(`update`), MONTH(`update`), DAY(`update`), HOUR(`UPDATE`) ORDER BY `update` ASC;
```

**Comment by pihome-shc** [comment]
@dvdcut that looks lot better.

**Comment by pihome-shc** [comment]
@dvdcut good work on #246, for future reference: may be add option to enable/disable graph

**Comment by pihome-shc** [comment]
update: 
i just updated my live system that runs on rpi 3 with very slow sd card and i wasn't expecting it to load in good time but it worked well.

**Comment by dvdcut** [comment]
no further updates required. i m closing this issue.
