### ISSUE TITLE
Improvement: Sensors/Zone Communication

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/pihome#25]
If your temperature sensor doesn't communicate or you have no temperature reading for a time:
during the night database clean-up removed old records, in result it get reading 0 and frost protection kicks in (it will probably keep going until the sensor starts working). Not good if you are on holidays.

**Suggestion:** Would be good if code could fault the zone if there is no temperature reading for a time or no comms with zone relay (so you don't turn on boiler when you can't communicate with zone controller), and then you have something in place to indicate zone fault on main screen.

For that one you probably need changes in boiler logic to mark zone fault, new column in zone table to mark it faulty for display on webpage and you need to force sending valid temperature reading from the sensor even if it didn't change from time to time.

**Comment by aszumski** [comment]
I'll work on that one next week.
