### ISSUE TITLE
Delete Nodes/Sensors from Settings

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/pihome#258]
Add option to delete nodes, sensors under settings->nodes and sensors.

**Comment by pihome-shc** [comment]
@dvdcut looks good, that disable button for used sensor is good thought. any further update on this?

**Comment by dvdcut** [comment]
@pihome-shc all done, you can close this issue.

**Comment by dvdcut** [comment]
added option to delete wired sensors.
