### ISSUE TITLE
mail notifications for rare scenarios

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/pihome#27]
On zone fail, sensor battery low, frost protection and over temperature.

**Comment by twa127** [comment]
Hi

Guess you have yet to add the supporting code in functions.php

**Comment by pihome-shc** [comment]
@twa127 there is not special function in functions.php file, notice.php requires notice table which was implemented while back. let me know if you have some specific errors. also notice.php isnt anywhere near finish right now it only collet sensors last seen and add records to notice table this table and notice.php itself requires some thinking, i m just throwing concept out there so i can get some feedback or may be some idea on how to do this right way from start. 

if you add following lines to notice.php to test email function you installing sendmail you'll get error in /var/mail/root
From MAILER-DAEMON  Sun Jun 16 22:33:37 2019
Return-Path: <MAILER-DAEMON>
Received: from localhost (localhost)
	by pihome (8.15.2/8.15.2/Debian-8) id x5GLXbpp014218;
	Sun, 16 Jun 2019 22:33:37 +0100
Date: Sun, 16 Jun 2019 22:33:37 +0100
From: Mail Delivery Subsystem <MAILER-DAEMON>
Message-Id: <201906162133.x5GLXbpp014218@pihome>
To: <root@pihome>
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="x5GLXbpp014218.1560720817/pihome"
Subject: Returned mail: see transcript for details
Auto-Submitted: auto-generated (failure)

This is a MIME-encapsulated message

--x5GLXbpp014218.1560720817/pihome

The original message was received at Sun, 16 Jun 2019 22:33:36 +0100
from pihome [127.0.0.1].......



$emailfrom = "'**root@pihom.local**'";
//email Setup for Notice 
$email = new PHPMailer();
$email->isHTML(true);
$mail->From = $emailfrom;
$mail->FromName = 'PiHome Smart Heating';
$email->AddAddress ('**youremail@domain.com**');
$email->Subject   = 'Notice - PiHome Smart Heating';
$email->Body      = 'This email is sent by PiHome Smart Heating <b> Local Hosted </b></br>';

return $email->Send();
if(!$mail->send()) {
	echo "\033[36m".date('Y-m-d H:i:s'). "\033[0m - Message could not be sent Mailer Error: ". $mail->ErrorInfo;
	exit;
} else {
    echo "\033[36m".date('Y-m-d H:i:s'). "\033[0m - Message has been sent";
}


-- structure for table pihome.notice
DROP TABLE IF EXISTS `notice`;
CREATE TABLE IF NOT EXISTS `notice` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sync` tinyint(4) NOT NULL DEFAULT '0',
  `purge` tinyint(4) NOT NULL DEFAULT '0',
  `datetime` datetime DEFAULT NULL,
  `message` varchar(200) COLLATE utf16_bin DEFAULT NULL,
  `status` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf16 COLLATE=utf16_bin;
