### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by twa127** [pihome-shc/pihome#283]
Hi,

Has anyone else noticed that homelist.php seems to have taken a massive performance hit over the last few days?

I think the problem is that we have swapped from using the mesages_in table to using messages_in_view_24h, if you agree I'll change homelist.php back to using the table

**Comment by pihome-shc** [comment]
Can we measure load time? I know moving to table view would definitely make it fast as it’s only going through last 24h data.

**Comment by twa127** [comment]
on my system with 24865 records in the table - browse messages_in took 0.01s and browse messages_in_view_24h took 1.01s

**Comment by pihome-shc** [comment]
here are the results from my system running on slow SD card, rpi 512mb ram. 
```
SELECT * FROM messages_in WHERE node_id = 21;
/* Affected rows: 0  Found rows: 665  Warnings: 0  Duration for 1 query: 0.187 sec. (+ 0.047 sec. network) */

SELECT * FROM messages_in_view_24h WHERE node_id = 21;
/* Affected rows: 0  Found rows: 179  Warnings: 0  Duration for 1 query: 0.172 sec. */

SELECT * FROM messages_in;
/* Affected rows: 0  Found rows: 14,327  Warnings: 0  Duration for 1 query: 0.016 sec. (+ 0.359 sec. network) */

SELECT * FROM messages_in_view_24h;
/* Affected rows: 0  Found rows: 3,763  Warnings: 0  Duration for 1 query: 0.125 sec. (+ 0.078 sec. network) */

```
raspberry pi 3 b+ on ssd disk 1gm ram,
```
SELECT * FROM messages_in WHERE node_id = 21;
/* Affected rows: 0  Found rows: 770  Warnings: 0  Duration for 1 query: 0.016 sec. (+ 0.031 sec. network) */

SELECT * FROM messages_in_view_24h WHERE node_id = 21;
/* Affected rows: 0  Found rows: 178  Warnings: 0  Duration for 1 query: 0.032 sec. */

SELECT * FROM messages_in;
/* Affected rows: 0  Found rows: 3,798  Warnings: 0  Duration for 1 query: 0.016 sec. (+ 0.109 sec. network) */

SELECT * FROM messages_in_view_24h;
/* Affected rows: 0  Found rows: 881  Warnings: 0  Duration for 1 query: 0.031 sec. (+ 0.016 sec. network) */
```

**Comment by pihome-shc** [comment]
here is from one customer with 16 zone with lot more records. 
```
SELECT * FROM messages_in WHERE node_id = 21;
/* Affected rows: 0  Found rows: 5,682  Warnings: 0  Duration for 1 query: 0.047 sec. (+ 0.203 sec. network) */

SELECT * FROM messages_in_view_24h WHERE node_id = 21;
/* Affected rows: 0  Found rows: 1,483  Warnings: 0  Duration for 1 query: 1.110 sec. (+ 0.296 sec. network) */

SELECT * FROM messages_in;
/* Affected rows: 0  Found rows: 44,247  Warnings: 0  Duration for 1 query: 0.016 sec. (+ 0.969 sec. network) */

SELECT * FROM messages_in_view_24h;
/* Affected rows: 0  Found rows: 10,680  Warnings: 0  Duration for 1 query: 0.156 sec. (+ 0.219 sec. network) */
```

**Comment by pihome-shc** [comment]
@twa127 how are you measuring your data. just query or one gui?

**Comment by twa127** [comment]
so it looks like using the view is not the thing to do and we should swap back to reading the table

**Comment by twa127** [comment]
just browsing the table/view using phpmyadmin

In practice opening the homelist screen is very very slow using the new version of homelist.php, replacing the view with the table restored the system back to its previous performance level

**Comment by aszumski** [comment]
Actually the temperature for active zones is available in zone_current_state table that we query anyway.
I've put in reading temperature from view just so we can get temperature for non active zones (not processed in boiler php).
We could do check if zone is enabled use value from zone_current_state and if it's not get temperature from messages/or view whatever is faster.
That should be best from performance side.

**Comment by twa127** [comment]
that sounds a good compromise to me, I have 3 active zones and 8 non-active, so still need the best performance to read messages_in, my vote is to go back to reading the data directly from the table

**Comment by pihome-shc** [comment]
@aszumski if in-active zone isnt processed by boiler.php then how temperature reading get to homelist? i always thought using table view with reduced number of records would be faster, on same note may be we can reduce number of days we keep records in message_in table.

**Comment by twa127** [comment]
I think performance is being governed by the date comparison. It takes longer to run a query against the view with its date comparison than it takes to run the query against all the records in the messages_in table. This is also causing problems with the graphs, where we run multiple queries against the same view

**Comment by pihome-shc** [comment]
if that is the case we can switch back to table instead of table view and also reduce the number of sensors reading from 3 days to 2 days. 
on same note if we query zone_current_state then it should be most fast method as its is only query one record and all the processing is already done in background by boiler.php

**Comment by twa127** [comment]
I suggest that we stick with getting the temperature from the messages_in table as this is simpler and we always have the latest reading without having to wait for boiler.php up update the zone_current_state table.

**Comment by aszumski** [comment]
Should we also change it in boiler.php ?
It uses view there, I know that user can't see the delay,
but faster is better.

**Comment by dvdcut** [comment]
my vote is to switch to table, i think reason view is slower it does two query, first to generate view and second run by user on view, @aszumski no harm to switch to table in boiler.php as well. 

on boiler.php to update zone_current_state with other bits, may be we need to implement this in better way so gui only depended on zone_current_state and we don't do any calculation or anything in homelist.php everything should come from zone_current_state, what you all think?

**Comment by dvdcut** [comment]
if i remember correctly zone_current_state was setup to bring boiler.php and homelist.php in sync

**Comment by twa127** [comment]
I'm running the latest homelist.php on my live system and now page loading is fine.  As I said above getting the temperature from the messages_in table is simpler and we always have the latest reading without having to wait for boiler.php up update the zone_current_state table,.

**Comment by pihome-shc** [comment]
Query temperature from messag_in would be faster as proven.

**Comment by pihome-shc** [comment]
@twa127 any further update/work required on this issue?
