### ISSUE TITLE
boiler.php not referencing the correct controller type

### ISSUE THREAD

**Issue by twa127** [pihome-shc/pihome#315]
The main zone loop does not save the value of the controller_type in the $zone_commands array, hence when the the zone_commands are executed they use the last zone processed value for every zone.

I've committed a fix

**Comment by pihome-shc** [comment]
@twa127  #314 is fix for this issue?

**Comment by twa127** [comment]
yep + a new view for the add-on logs

**Comment by twa127** [comment]
as it turns out I probably don't need the new view, I'm working on being able to override a category 2 zone schedule while it's running, ie. lamp is scheduled to be ON but you decide to go out so want to be able to switch OFF without the schedule turning it back ON the next time boiler.php cycles.

**Comment by twa127** [comment]
I think tis can now be closed
