### ISSUE TITLE
Zone shedule with conditional/coop start

### ISSUE THREAD

**Issue by aszumski** [pihome-shc/pihome#32]
Idea is to have option in the schedule for the zone to have contitional/coop cut in.

Probably no big use for it if you have 3 zones, but might be handy for example for hot water, it makes more sense with multiple zones like I plan to have, with 8 zones there will be one of them cutting in after the other so probably boiler will run all the time.

Idea is that if zone has conditional/coop schedule active it won't start even if it's below setpoint, it will only start if it's below setpoint and boiler is already running and then finish normally when sp is reached even if zones that enabled start of it finished heating.

So basically let's say during day I control temperature downstairs on normal schedule, and attic and bedrooms cut in only when they are below temperature and downstairs cut in.
Same during the night I have normal zone control in bedrooms and rest of the house is conditional start, basically temperatures I don't care about that much start only when the ones I care about more are already running.

Same can be used for hot water, thee ate periods when you want hot water, morning, evening for shower (use normal schedule then), but for rest of the day don't start boiler if only request is hot water, wait for other zone that has normal schedule to start and heat it together.

**Comment by pihome-shc** [comment]
@aszumski 
that mean all other zone start heating for set point/temperature? would that not cause heat loss? i.e in that case boiler have to heat rest of the zone as well hence longer boiler running time, i think as far as hot water goes it would be good improvement. 

i have implemented override for somewhat same function but right now override is broken (i havent tested it though)

**Comment by aszumski** [comment]
It would work same as any other schedule except for  zone starting.
What I'm thinking of is when you set up schedule after enabling zone for that schedule you select temperature and you can select thick box for conditional/coop start.

**Comment by pihome-shc** [comment]
@aszumski Thank you for pull request.
