### ISSUE TITLE
Wired DS18B20 Sensors and Graphs 

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/pihome#325]
[PiHome Link to comments](https://www.pihome.eu/2020/05/24/pihome-version-1-75/#comment-59810)
Hi,
When I first installed the software it did not find the 1-wire temperature sensors, I had to manually run 'python gpio_ds18b20.py ' to discover the temperature sensors, this worked correctly and they are still being logged to message_in_view_24 in the database. Based on your feedback above I manually ran 'python gateway.py' but it just times out. I do not have a wifi gateway as all my sensors are directly connected using 1-wire and all my zones are directly connected to the gpio. Is there something else I need to configure or something I can check to help locate the problem?
Thanks in advance, Harvey

**Comment by dvdcut** [comment]
partial fix is to un-comment the cronjob, and all code is there for users, i know current code do not update zone_graph table.  i think few more lines can fix this fully. i can work on this one later on.

**Comment by dvdcut** [comment]
this pull request should fix this issue.
