### ISSUE TITLE
Cronjob management

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/pihome#327]
while working on #325 it got me thinking about cronjobs, can we manage these jobs some other way. i mean one script manage all cronjobs and it runs once every 60seconds this way we'll have only one entry in crobtab? we can control this from web interface what to run and how frequent. 
This is just very vague question so any reason we shouldn't do this? or any suggestion to do this?

**Comment by pihome-shc** [comment]
@dvdcut i looked at this in the past but due to time constrains i never had chance to revisit this. there are some project on github written in php.

**Comment by dvdcut** [comment]
i think all cron jobs can be managed from one php script and all jobs with schedule can be saved in database, small modification to exiting crontab table, i will try to find something on github so i don't have re-invent the wheel 😄 

```
CREATE TABLE `crontab` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`status` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`min` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`hour` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`day` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`month` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`weekday` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`command` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`output` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`last_run` DATETIME NULL DEFAULT NULL,
	`comments` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`id`) USING BTREE
)
COMMENT='PiHome Smart Heating - Manage Crontab from web interface '
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;
```

**Comment by pihome-shc** [comment]
feel free to work on this, i'll try to give you my input if needed.

**Comment by sandreialexandru** [comment]
```
# Schedule Library imported 
import schedule 
import time 
import os

# Functions setup 
def system_c(): 
    system = os.popen("usr/bin/php /var/www/cron/system_c.php \n") 
    system_output = system.read()
    print(system_output)
    
def system_c_exec():
    return system_c()
    
def weather_update(): 
    weather = os.popen("/usr/bin/php /var/www/cron/weather_update.php \n")
    weather_output = weather.read()
    print(weather_output) 
    
def weather_update_exec():
    return weather_update()
    
def reboot_wifi(): 
    rwifi = os.popen("sh /var/www/cron/reboot_wifi.sh \n") 
    rwifi_output = rwifi.read()
    print(rwifi_output)
    
def reboot_wifi_exec():
    return reboot_wifi()
    
def check_gw(): 
    chk_gw = os.popen("php /var/www/cron/check_gw.php \n")
    chk_gw_output = chk_gw.read()
    print(chk_gw_output)
    
def check_gw_exec():
    return check_gw()
    
def boiler(): 
    stream = os.popen("/usr/bin/php /var/www/cron/boiler.php \n")
    boiler_output = stream.read()
    print (boiler_output)
    
def boiler_exec():
    return boiler()
    
def selfservice(): 
    self = os.popen("/usr/bin/php /var/www/cron/selfservice.php \n")
    self_output = self.read()
    print (self_output)
    
def selfservice_exec():
    return selfservice()
    
# Task scheduling 

schedule.every(10).minutes.do(system_c)
schedule.every(30).minutes.do(weather_update) 
schedule.every(2).minutes.do(reboot_wifi) 
schedule.every(2).minutes.do(check_gw) 
schedule.every(1).minutes.do(boiler) 
#schedule.every(3).seconds.do(selfservice) 

# Loop so that the scheduling task 
# keeps on running all time. 

while True: 
  
    # Checks whether a scheduled task  
    # is pending to run or not 
    
    schedule.run_pending() 
    time.sleep(1) 
```

This is my approach to a python script that does a better job at scheduling than cron.
Having a GUI for management requires values (time, job command, command output...) to be stored into variables that get updated from the database.  The python script can then be run at startup with rc.local
What do you think?

**Comment by sandreialexandru** [comment]
Update:
```
CREATE TABLE `jobs` (
  `id` int(11) NOT NULL,
  `name` char(50) NOT NULL,
  `script` char(100) NOT NULL,
  `time` int(11) NOT NULL,
  `output` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

Python script to run on boot:

> We need to install schedule (pip3 install schedule)

```
# Schedule Library imported 
import schedule 
import time 
import os
import configparser
import MySQLdb as mdb

# Initialise the database access variables
config = configparser.ConfigParser()
config.read('/var/www/st_inc/db_config.ini')
dbhost = config.get('db', 'hostname')
dbuser = config.get('db', 'dbusername')
dbpass = config.get('db', 'dbpassword')
dbname = config.get('db', 'dbname')

con = mdb.connect(dbhost, dbuser, dbpass, dbname)
cur = con.cursor()

# Functions setup 
def system_c(): 
    system = os.popen("php /var/www/cron/system_c.php \n") 
    system_output = system.read()
    #print(system_output)
    cur.execute("""UPDATE jobs SET output = %s WHERE name = 'system_c'""", [system_output])
    con.commit()

systemtime = cur.execute("""SELECT `time` FROM `jobs` where `name` = 'system_c'""") 
    
def weather_update(): 
    weather = os.popen("php /var/www/cron/weather_update.php \n")
    weather_output = weather.read()
    print(weather_output) 
    cur.execute("""UPDATE `jobs` SET `output` = %s WHERE `name` = 'weather_update'""", [weather_output])
    con.commit()

weathertime = cur.execute("""SELECT `time` FROM `jobs` where `name` = 'weather_update'""")
 
    
def reboot_wifi(): 
    rwifi = os.popen("sh /var/www/cron/reboot_wifi.sh \n") 
    rwifi_output = rwifi.read()
    print(rwifi_output)
    cur.execute("""UPDATE `jobs` SET `output` = %s WHERE `name` = 'reboot_wifi'""", [rwifi_output])
    con.commit()

reboottime = cur.execute("""SELECT `time` FROM `jobs` where `name` = 'reboot_wifi'""") 
    
def check_gw(): 
    chk_gw = os.popen("php /var/www/cron/check_gw.php \n")
    chk_gw_output = chk_gw.read()
    print(chk_gw_output)
    cur.execute("""UPDATE `jobs` SET `output` = %s WHERE `name` = 'check_gw'""", [chk_gw_output])
    con.commit()

checktime = cur.execute("""SELECT `time` FROM `jobs` where `name` = 'check_gw'""")   
    
def boiler(): 
    boiler = os.popen("php /var/www/cron/boiler.php \n")
    boiler_output = boiler.read()
    print (boiler_output)
    cur.execute("""UPDATE `jobs` SET `output` = %s WHERE `name` = 'boiler'""", [boiler_output])
    con.commit()

boilertime = cur.execute("""SELECT `time` FROM `jobs` where `name` = 'boiler'""") 
     
# Task scheduling 

schedule.every(systemtime).seconds.do(system_c)
schedule.every(weathertime).seconds.do(weather_update) 
schedule.every(reboottime).seconds.do(reboot_wifi) 
schedule.every(checktime).seconds.do(check_gw) 
schedule.every(boilertime).seconds.do(boiler) 

# Loop so that the scheduling task 
# keeps on running all time. 

while True: 
  
    # Checks whether a scheduled task  
    # is pending to run or not 
    
    schedule.run_pending() 
    time.sleep(1) 

```

The script pulls the time (in seconds) from the database and runs the tasks repeatedly. The output of the task is inserted into the database at every run.

**Comment by pihome-shc** [comment]
@sandreialexandru can you attached python file with ticket, you can attached it as zip file.

**Comment by sandreialexandru** [comment]
I shall attach the file soon. 
The next step would be a user interface to update time values in the database and see the output of the scheduled scripts.

**Comment by sandreialexandru** [comment]
Here is my approach to running jobs at a schedule in python
[jobs.zip](https://github.com/pihome-shc/pihome/files/5393789/jobs.zip)

**Comment by sandreialexandru** [comment]
Any thoughts on this?

**Comment by pihome-shc** [comment]
@sandreialexandru very interesting 
it takes reading from jobs table and python scripts runs as service? i think we need to implement this in a way so we can see the status under settings that it is running.

**Comment by sandreialexandru** [comment]
I've updated the file and the script should check itself to see if it is running. This is some kind of a paradox but if script is running it outputs the result of the bash command (`pid='pgrep -f jobs.py' ; ps -o start,etimes -p $pid`) to database. The result should  look like this :
**STARTED ELAPSED
01:12:15          16
01:12:31          0**
Having this output doesn't mean that the script is still running, but making another script to check the status of another one doesn't make any sense. With this information we can check if the script is running by observing the updates in the database(or in the web UI).
The table "system" would need another column script_output. Feel free to edit line 84 if you think it is needed.

**Comment by pihome-shc** [comment]
@sandreialexandru very good work but its not good to have all schedules hardcoded, it would be best to get data from database and run command as is from database and do this whole think as loop rather then hard coded command in the code so if user wants to have something different or add extra cronjobs then user gets option to do this on the gui. 
suggested table structure.:
id, record number 
status, (1 enable, 0 disable)
name,  (cosmetic name)
script,  php /var/www/cron/weather_update.php (full path to command and script to run)
time, (how frequent to run job, (to keep it simple take this value as minutes) 
output_status, user can enable/disable output (1 enable, 0 disable)
output, if output_status is set to 1 then save output otherwise dont save. 

```
schedule.every(systemtime).seconds.do(system_c)
schedule.every(weathertime).seconds.do(weather_update) 
schedule.every(reboottime).seconds.do(reboot_wifi) 
schedule.every(checktime).seconds.do(check_gw) 
schedule.every(boilertime).seconds.do(boiler) 
schedule.every(5).seconds.do(script_check)
```

**Comment by dvdcut** [comment]
moved to new version (MaxAir)
https://github.com/pihome-shc/PiHomeHVAC/issues/34
