### ISSUE TITLE
Issue since v1.76 update

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/pihome#364]
Received this from one user. 

Hats off to you and the team on the latest release. Its really getting slick.

I've been following the github discussions with interest, and updated from 1.75 to 1.76 as soon as you sent the notification.

I noticed a few things since the update - but I'm not very familiar with github - I didn't know if I should raise these queries as bugs, but I figured I'd run them by you.

Issue since v1.76 update:
- Graphs no longer showing temperature - despite sensor's saving temp readings to database (otuside temp + cpu temp graphs are working fine though.
- 'network settings' blank in database - no new row created via migrate or update php scripts (I manually added an entry)
- 'node_id' blank in database - no new row created via migrate or update php scripts  
- 'zone_graphs' blank in database - no new row created via migrate or update php scripts    I tried out the tasmota set-up - but i note that a number of the menu's in 'Settings' do not seem to save - so I have manually added the http command settings via phpmyadmin. For now the home gui is showing my tasmota relay's cycling on/off - but the command issued via pihome do not seem to be working I will need to dig into this further to see if I can figure out what is happening).

Kind regards,

**Comment by twa127** [comment]
Hi,

Not sure why the graphs should be a problem
Network settings table not effected by either migrate or update so should remain in the same state as before or be empty
Not sure what you mean about node_id
zone_graphs table should not be effected by either migrate or update, I'll investigate
I fixed the http message GUI yesterday #360

**Comment by twa127** [comment]
I think I can see the problem with the zone graphs, the query in gateway.py need to be amended to reflect the split zone table, I'll sort this out asap

**Comment by twa127** [comment]
The current version of gateway.py uses absolute values to reference the columns in the select query used for zone_graphs table, I'll change this to reference the columns by name, just in case this is causing a problem

**Comment by twa127** [comment]
the node_id table was added at #321 MySensors Nodes without ID and is populated as required by gateway.py

**Comment by scottagecheeseandcrackers** [comment]
Hey guys - in the interest of working out any kinks - here is my SQL database backup from prior to the update. I hope this helps.
[pihome_2020-08-05_08-27-35.zip](https://github.com/pihome-shc/pihome/files/5037040/pihome_2020-08-05_08-27-35.zip)

@twa127 - I gave the sonoff / tasmota add-on a try. I managed to set-up a hallway lamp. The add 'zone http message' button would not allow me to save the power on command via the GUI. I tried adding the http message manually through phpmyadmin. If i locally login to my tasmota and cycle it - the pihome gui updates to show the state - but clicking the 'hallway lamp' symbol via pihome does not cycle the tasmota. I may need to dig further into this to figure out what is going on.

**Comment by pihome-shc** [comment]
@twa127 graph issue is fixed after #365

**Comment by twa127** [comment]
hi
@scottagecheeseandcrackers  I notice there is no 'zone_graphs' table in your database dump.

After #360 update you may need to delete your browser history to pickup the change to js/request.js, this should fix the http message GUI

**Comment by twa127** [comment]
@scottagecheeseandcrackers when trying to debug your Sonoff, the first thing to check is that you have an entry in the messages_out table, this should have been created by the Add Zone process. Example below shows id = 92 entry for the Sonoff zone. You can manually set the Sonoff state by setting the payload to either 'Power ON' or 'Power OFF' and setting 'sent' to 0, gateway.py will then set the Sonoff the next time it cycles. Hope that helps
![Capture](https://user-images.githubusercontent.com/46624596/89617287-d7bba080-d881-11ea-9a87-bf5931455ee3.JPG)

**Comment by pihome-shc** [comment]
Any more work needed for this issue or. Can I close this issue?

**Comment by twa127** [comment]
I think we have solved the issues mentioned in the original post

**Comment by scottagecheeseandcrackers** [comment]
Apologies guys - was under a rock - missed the messages above.

@twa127  - Sonoff issue fixed with #360 - many thanks - really cool feature (I now have to see how many things around the house I can tasmota-ize)

zone_graphs is showing readings for the majority of my temperature sensors (for some reason one of them is missing)
But the graphs on the gui only show 2 temperature readings.
Also I'm not sure if you have implemented the battery voltage graph yet - but that too is blank.

**Comment by pihome-shc** [comment]
@scottagecheeseandcrackers zone type nme are hard coded as heating and water make sure you have these two names as heating and water

**Comment by twa127** [comment]
should have been no impact on battery voltage graphs, do you have anything in the nodes_battery table?

**Comment by scottagecheeseandcrackers** [comment]
> @scottagecheeseandcrackers zone type nme are hard coded as heating and water make sure you have these two names as heating and water

@pihome-shc - my zone type table has these listed as 'Heating' and 'Hot Water'

![Screenshot_20200808-153705_Chrome](https://user-images.githubusercontent.com/16407242/89713125-87ca0000-d98d-11ea-8846-40ab58cb49cf.jpg)

**Comment by scottagecheeseandcrackers** [comment]
> should have been no impact on battery voltage graphs, do you have anything in the nodes_battery table?

@twa127 - nodes_battery table fully populated for all sensors.

**Comment by pihome-shc** [comment]
Change hot water to water in zone_type table

**Comment by twa127** [comment]
Hi,

That's not going to work for all the current records in the zone_graphs table, might be a good idea to change the string test to look for sub-strings 'heating, 'water' and 'Immersion'

**Comment by scottagecheeseandcrackers** [comment]
Sorry @twa127 - that went over my head...

**Comment by twa127** [comment]
he he

Try using this for chart_load.php
[chart_load.zip](https://github.com/pihome-shc/pihome/files/5045443/chart_load.zip)

**Comment by twa127** [comment]
I've looked at chart_batteryusage.php again and still can't see anything which should cause you to loose them after migrating the database. Can you post the first few records from your nodes_battery table please

**Comment by scottagecheeseandcrackers** [comment]
@twa127 
#
![Screenshot_20200808-184900_Chrome](https://user-images.githubusercontent.com/16407242/89716789-fddb6080-d9a7-11ea-96e6-b57583a5ae1c.jpg)

**Comment by twa127** [comment]
That looks fine, I'll investigate further, did the updated chart_load.php fix your missing temperatures?

**Comment by twa127** [comment]
Can you send me a screen shot of your nodes table please

**Comment by scottagecheeseandcrackers** [comment]
> That looks fine, I'll investigate further, did the updated chart_load.php fix your missing temperatures?

Just rebooted the system to see any changes - I can now see my hot water temp reading alongside the outside temp.

Still missing a sensor reading though - perhaps it will appear as new readings are received.

**Comment by scottagecheeseandcrackers** [comment]
![Nodes_table_snip](https://user-images.githubusercontent.com/16407242/89717099-0da87400-d9ab-11ea-8422-a8725e40b3cd.JPG)

**Comment by twa127** [comment]
ah there is a check in chart_batteryusage.php for a valid min_value

$querya ="select * from nodes where `type` = 'MySensor' AND `name` LIKE '%Sensor' AND `min_value` <> 0;";

you need to set a min_value for all your nodes which are battery powered, hopefully that should fix the problem

**Comment by scottagecheeseandcrackers** [comment]
Is the min_value for voltage or temp?

**Comment by twa127** [comment]
% battery level threshold say for example 75, when the level falls below 75% it triggers a notification

**Comment by scottagecheeseandcrackers** [comment]
> % battery level threshold say for example 75, when the level falls below 75% it triggers a notification

That fixed the voltage charts. Thanks

**Comment by twa127** [comment]
great, so you happy with 1.76 now?

**Comment by scottagecheeseandcrackers** [comment]
> great, so you happy with 1.76 now?

Great work. Fantastic build. Its really starting to out-perform other platforms.

**Comment by twa127** [comment]
glad you like it :-)
