### ISSUE TITLE
max_operation_time for zones

### ISSUE THREAD

**Issue by twa127** [pihome-shc/pihome#366]
Hi,

I've introduced a small issue with the change to the zone table. 

I've placed max_operation_time in the new zone_sensors_table but left in on the zone add/edit screen for all zones. The issue is that when adding/edititing cat2 zones the zone_sensors_table is not updated.

Not too much of a problem as for as far as I can see the value is not currently used anywhere. 

There are 2 possible solutions

1. Remove max_operation_time input from the zone add/edit screen for cat2 zones
2. Move max_operation_time from the zone_sensors_table to the zone_table

I personally think 2 is better as maybe max_operation_time might be useful as a safety feature for all zone categories.

Any thoughts?

**Comment by pihome-shc** [comment]
@twa127 yes i agree 2nd option is better.

**Comment by pihome-shc** [comment]
@twa127 any further update required for this issue?

**Comment by twa127** [comment]
No I think all resolved now
