### ISSUE TITLE
Use Sunset for Cat2 Zone Schedule Start Time

### ISSUE THREAD

**Issue by twa127** [pihome-shc/pihome#381]
What do you think about having the option to use the sunset time available from weather as a schedule start time. Thought it might be useful to have lamps scheduled to come on at sunset.

**Comment by pihome-shc** [comment]
What if users don’t have weather api set?

**Comment by twa127** [comment]
Just make it optional, so no weather api then dont select or maybe check for weather api

**Comment by pihome-shc** [comment]
no doubt it would be good option for sun set/sun rise.

**Comment by twa127** [comment]
This what I have -

1. Add new field to 'enable_sunset' to table 'schedule_daily_time'
2. In boiler.php and scheduling.php use getWeather() function to return current weather
3. if returns 0 then functionality remains as before
4. if returns data the enable new checkbox in scheduling.php to enable sunset override of start time when start time value is set to some value later than sunset ie set the same as stop time. If start time is set to a value before sunset the start event occurs at this time rather than sunset.
5. in boiler.php if getWeather() returns a valid time earlier than start time then this triggers the schedule start

![sched1](https://user-images.githubusercontent.com/46624596/91532332-120ae180-e906-11ea-994a-1db16d86025c.JPG)

**Comment by twa127** [comment]
Attached something for you to test. You need to add a new field to the schedule_daily_time table, call it enable_sunset with a type of TINYINT 1

I've changed the validation from using getWeather() to reading the weather table and checking it has been updated in the last hour.

[sunset.zip](https://github.com/pihome-shc/pihome/files/5142277/sunset.zip)

**Comment by twa127** [comment]
Fix for boiler.php query not checking time variable correctly
[boiler.zip](https://github.com/pihome-shc/pihome/files/5144876/boiler.zip)

**Comment by pihome-shc** [comment]
Gui works as expected, but i have errro while creating schedule 

```
Zone Record Add/Update Failed:

Cannot add or update a child row: a foreign key constraint fails (`pihome`.`schedule_daily_time_zone`, CONSTRAINT `FK_schedule_daily_time_zone_schedule_daily_time` FOREIGN KEY (`schedule_daily_time_id`) REFERENCES `schedule_daily_time` (`id`))
```

**Comment by pihome-shc** [comment]
ignore my last comments, i was modifying wrong database (enable_sunset ) but after switching to right one it worked :) 
one suggestion though, can we add sun rise icon in front of the zone name on schedule list.

**Comment by twa127** [comment]
How about
![sched2](https://user-images.githubusercontent.com/46624596/91636749-e9b0df00-e9fa-11ea-8570-749a0ca58b27.JPG)

**Comment by pihome-shc** [comment]
I think sunrise just before schedule name would be better same way we have coop icon.

**Comment by twa127** [comment]
Can't say I'm keen in this
![sched3](https://user-images.githubusercontent.com/46624596/91637222-eddefb80-e9fe-11ea-84ff-4abddf8e1cb0.JPG)

**Comment by pihome-shc** [comment]
I wasn’t expecting it look like this, :( also do we have sunrise icon ?

**Comment by twa127** [comment]
I think it looks better to keep the zone names in the same position, so icon would look better in the circle or after the name. The icon should really be sunset not sunrise, I'm sure we can find something suitable. This looks slightly better, but still prefer the first attempt

![sched4](https://user-images.githubusercontent.com/46624596/91640544-3c4bc480-ea16-11ea-9c43-1909c01a8b24.JPG)

**Comment by twa127** [comment]
Lost my internet for a few hours ;-( how about
![sched5](https://user-images.githubusercontent.com/46624596/91640665-2f7ba080-ea17-11ea-8635-11b15d066296.JPG)

**Comment by pihome-shc** [comment]
@twa127 last one is awesome love it,

**Comment by twa127** [comment]
ok happy for me to commit ?

**Comment by pihome-shc** [comment]
Yes, definitely, update the build number as well.

**Comment by twa127** [comment]
I found a bug in boiler.php, I'll test the fix before I commit

**Comment by twa127** [comment]
Hi,

After using this feature for a bit I've come up with a revised version -

1. Allows individual selection of sunset override rather than applying globally to the zone
2. Enable the use of an offset value, to say turn on x minutes before sunset

What do you think ?

![sched6](https://user-images.githubusercontent.com/46624596/91747202-afd80800-ebb5-11ea-882d-d312e9454a32.JPG)

**Comment by pihome-shc** [comment]
@twa127 good thinking for individual zone, i think change line from Enable Sunset and set Offset in Minutes change it to Sunset & set Offset in Minutes. it looks very impressive.

**Comment by twa127** [comment]
Okay, the basic idea was to make it similar to Coop selection. Now need to work out the backend to change from zone based to controller based

**Comment by twa127** [comment]
Please note the table format for schedule_daily_time and schedule_daily_time_zone has been changed for this update, also view schedule_daily_time_zone_view has been changed
