### ISSUE TITLE
Charts not resetting - showing more than 24 hours

### ISSUE THREAD

**Issue by scottagecheeseandcrackers** [pihome-shc/pihome#384]
![20200830_093611](https://user-images.githubusercontent.com/16407242/91655034-c727d000-eaa5-11ea-95ba-f36ddec9c4c1.jpg)
 
Since the update to v1.76 it seems the charts x-axis is showing multiple days. Maybe this is just a scaling issue?

Also I have noticed that the boost icon is no longer showing on the home page.
![SmartSelect_20200830-094320_Chrome](https://user-images.githubusercontent.com/16407242/91655094-2e458480-eaa6-11ea-9301-e1014415b65a.jpg)
This screenshot is taken with a boost running on zone Ch. Hot Water.

**Comment by pihome-shc** [comment]
@scottagecheeseandcrackers zone graphs are missing due to missing values for that time, can you check zone_graph table. for boost icon, can you check zone_current_state table, you can remove all records from zone_current_state and they will get created in next boiler.php run.

**Comment by scottagecheeseandcrackers** [comment]
@pihome-shc - you are correct, zone graphs data missing for those times/days. The issue seems to be that the graph starts from over 3 days ago and each day it zooms out further and further. It looks like the zone data starts from the last dB cleanup, but the graph is still showing multiple days before the last cleanup. Zone graph data also missing for a number of zones, even though the temperature are shown in the home gui. 

On the zone_current_state query, I deleted those records and ran a boost to test...no change. Boiler icon changes but no boost icon for any zones. Zone_current_state table looks likes its missing data for me.

![SmartSelect_20200830-133439_Chrome](https://user-images.githubusercontent.com/16407242/91659203-75dc0880-eac6-11ea-9b26-ec8255867be7.jpg)

**Comment by pihome-shc** [comment]
Can you exports database and attach here.

**Comment by scottagecheeseandcrackers** [comment]
Link to download database file - https://we.tl/t-zacF8H8avu

**Comment by twa127** [comment]
easier for me if you mysqldump eg

mysqldump -u root -ppassw0rd pihome > dump.sql

**Comment by scottagecheeseandcrackers** [comment]
@twa127 - once again thank you for all the help (also @pihome-shc )

[dump.zip](https://github.com/pihome-shc/pihome/files/5147316/dump.zip)

**Comment by twa127** [comment]
first thing is I can't open any views

![scott1](https://user-images.githubusercontent.com/46624596/91668845-d63f6a00-eb07-11ea-843b-e35fe3b55a65.JPG)

**Comment by twa127** [comment]
re-created the views and that fixed the problem, next thing - you have multiple sensors connected to zones 33, 34 and 35, I guess that is not what you intended
![scott2](https://user-images.githubusercontent.com/46624596/91669093-20c1e600-eb0a-11ea-80d3-9a75866d89bd.JPG)

**Comment by twa127** [comment]
explains why you have 2 Ch Hot Water graph zones

**Comment by scottagecheeseandcrackers** [comment]
@twa127 - I use HeidiSQL typically - for some strange reason it refuses to let me log-in as 'phpmyadmin' using the default password. Yet if I open 192.168.0.129/phpmyadmin - the same login detail work fine. Deleted those extra rows in zone_sensors...no change that I can see yet.

**Comment by scottagecheeseandcrackers** [comment]
@twa127 - after a bit of sensor cleanup in the zone_sensors table - and a good cache clearing - seems to be looking better

![image](https://user-images.githubusercontent.com/16407242/91669932-ca0bda80-eb10-11ea-944a-d12aa89e4457.png)

Hopefully the missing sensors will populate in the graph now that the correct sensors have been assigned to the right zones.

Any idea why the boost symbol wouldn't be loading.

**Comment by twa127** [comment]
not yet :-) please post a copy of your cleaned-up database

**Comment by scottagecheeseandcrackers** [comment]
[pihome.zip](https://github.com/pihome-shc/pihome/files/5147509/pihome.zip)

Hope this sheds a little a light...

**Comment by twa127** [comment]
one thing about the boost icon is that it now does not appear immediately but after boiler.php as executed

**Comment by twa127** [comment]
can you do a mysqldump please

**Comment by scottagecheeseandcrackers** [comment]
[dump.zip](https://github.com/pihome-shc/pihome/files/5147527/dump.zip)

**Comment by twa127** [comment]
You have multiple entries  in the boost table for the same zone_id

**Comment by scottagecheeseandcrackers** [comment]
Yes - I have different boost option set (ie. Ch. Hot Water boost for 30 mins or Ch. Hot Water boost for 60 mins)

**Comment by twa127** [comment]
Problem is in the nodes table id 26 status is NULL, should be Active, after changing this the zone_current_state table updates okay and boost indicator is shown

**Comment by scottagecheeseandcrackers** [comment]
@twa127 - Bingo that fix did the trick - Boost icon now showing - last one to fix is the charts.

**Comment by twa127** [comment]
where are we now with the charts ?

**Comment by scottagecheeseandcrackers** [comment]
Last cache clear reset the graphs, but they seem to be still showing more than 24hours. Few sensors remain missing despite data in 'messages_in'. No sign of graphs in battery.

![SmartSelect_20200831-193135_Chrome](https://user-images.githubusercontent.com/16407242/91754169-e0716f00-ebc0-11ea-9ec1-050b25df1921.jpg)
![SmartSelect_20200831-193158_Chrome](https://user-images.githubusercontent.com/16407242/91754195-ecf5c780-ebc0-11ea-9908-df7a6aab6302.jpg)

**Comment by twa127** [comment]
Battery graph problem is due to an error in the nodes table, the type value should be MySensor not MySensors

**Comment by twa127** [comment]
The data for the zone graphs comes from the zone_graphs table

**Comment by twa127** [comment]
Your zone_sensors table does not look correct, you have duplicate entries and sensors allocated to more than 1 zone eg id 34 and 39 are duplicates, id 42 allocates the same sensor (24-0) to a second zone

**Comment by scottagecheeseandcrackers** [comment]
I have set up a ground floor zone - which uses the same sensor as the living room. (The hope original hope was that if I hit boost on this zone it would act as the overall controller - but must have all zones active for boiler to kick )  in either case zone id 33 and 34 are set not to appear in the graphs via the gui.

**Comment by twa127** [comment]
okay, have we fixed the battery graph ?

**Comment by twa127** [comment]
gateway.py should update the zone_graphs table which is used by chart_load.php to load the active zone graphs

**Comment by scottagecheeseandcrackers** [comment]
> okay, have we fixed the battery graph ?
> 

Yep battery graph fixed with the MySensors typo.

**Comment by scottagecheeseandcrackers** [comment]
> gateway.py should update the zone_graphs table which is used by chart_load.php to load the active zone graphs

Should I manually run 'gateway.py' to see if this fixes it?

**Comment by pihome-shc** [comment]
@scottagecheeseandcrackers gateway.py runs in background anyway.

**Comment by twa127** [comment]
If I ran a query against the zone_graphs table you can see no entries for Master Bedroom and only old entries for Kitchen, these are the missing graphs over the last 24 hours. For some reason gateway.py is not updating the zone_graphs table for these 2 zones
![scott3](https://user-images.githubusercontent.com/46624596/91810946-a935a900-ec26-11ea-84df-b8d1ff3afd07.JPG)

**Comment by twa127** [comment]
Are you sure sensor ID 23 and 24 are set correctly in the zone_sensors table

1. Sensor 23 allocated to Master Bedroom and Living Room
2. Sensor 24 allocated to Ground Floor twice and Kitchen

**Comment by twa127** [comment]
Can you please let me know which nodes you have allocated to each zone

**Comment by twa127** [comment]
I went back to the database you posted pihome_2020-08-25_06-23-58.sql and the zone_sensors table looks much more sensible in this one
![scott4](https://user-images.githubusercontent.com/46624596/91814447-0bdd7380-ec2c-11ea-9bf1-4925ef1bcc89.JPG)

**Comment by twa127** [comment]
I think your problem with the graphs displaying more than the last 24 hours is because gateway.py is failing to process the zone_graphs table where it deletes anything older than 24 hours., this is probably due to the errors in the zone_sensors table data.

**Comment by scottagecheeseandcrackers** [comment]
Apologies for the delayed response. @twa127 - you were correct - more than 1 zone with the same sensor was causing the havoc. As soon as I deleted Zone_id 33 and 34, cleared previous graph data and cleared my cache everything looks right.

Dump file attached below - hopefully this is all the issues sorted. Thanks again for the assistance.

![GUI](https://user-images.githubusercontent.com/16407242/91910754-7ed80000-eca7-11ea-92cf-206a307ee2f8.JPG)

![Chart](https://user-images.githubusercontent.com/16407242/91910769-84cde100-eca7-11ea-973e-837f3d35ead2.JPG)

[dump (2).zip](https://github.com/pihome-shc/pihome/files/5159047/dump.2.zip)

**Comment by twa127** [comment]
no problem, glad its sorted
