### ISSUE TITLE
Piconnect

### ISSUE THREAD

**Issue by twa127** [pihome-shc/pihome#395]
Hi,

I'm a bit confused looking at piconnect.php, its function now appears to be table maintenance, perhaps the name is now not appropriate.

**Comment by pihome-shc** [comment]
@twa127 yes you are right, at this time it is more of table maintenance. you are thinking to rename it?

**Comment by twa127** [comment]
yes perhaps but maybe the sequence could be done in db.php ie rather than setting purge in db.php why not do the deletions

**Comment by pihome-shc** [comment]
yes but once PiConnect become available to general public we dont have to modify main software hence leaving this delete in piconnect.php file.

**Comment by twa127** [comment]
ah, so would you prefer to leave it as it is for now?

**Comment by pihome-shc** [comment]
yes, better to leave it as it is.

**Comment by twa127** [comment]
Okay, I'll close this issue
