### ISSUE TITLE
Clicking on temperature circle deletes the schedule

### ISSUE THREAD

**Issue by sandreialexandru** [pihome-shc/pihome#425]
Clicking on temperature circle in the zone modal deletes the schedule  instead of disabling it.

**Comment by pihome-shc** [comment]
@sandreialexandru temperature circle have href="javascript:active_schedule(<schedule_daily_time_id>);" can you check if you have same href or different?

**Comment by sandreialexandru** [comment]
![16045372056805937282219734353450](https://user-images.githubusercontent.com/45868553/98183613-304a1a80-1f11-11eb-8e37-4664a91df389.jpg)
This is how I have it. If I change it like you say it does not do anything.

**Comment by pihome-shc** [comment]
is that [schedulelist.php ](https://github.com/pihome-shc/pihome/blob/master/schedulelist.php) ? can you check if you have latest version

**Comment by sandreialexandru** [comment]
It is homelist.php
The schedule under the modal popup window (near OneTouch) gets deleted when clicking on temperature circle.
In schedulelist.php work OK.

**Comment by pihome-shc** [comment]
if you have only one zone enabled in any schedule and you disable that zone from dashboard then schedulelist do not display that but it stays in db. it is bug in schedulelist.php

**Comment by pihome-shc** [comment]
line 57 need to  change from 

```
SELECT time_id, time_status, `start`, `end`, WeekDays,tz_id, tz_status, zone_id, index_id, zone_name, `category`, temperature, FORMAT(max(temperature),2) as max_c, sch_name, max(sunset) AS sunset FROM schedule_daily_time_zone_view WHERE holidays_id = 0 AND tz_status = 1 group by time_id ORDER BY start, sch_name asc
```
to 

```
SELECT time_id, time_status, `start`, `end`, WeekDays,tz_id, tz_status, zone_id, index_id, zone_name, `category`, temperature, FORMAT(max(temperature),2) as max_c, sch_name, max(sunset) AS sunset FROM schedule_daily_time_zone_view WHERE holidays_id = 0 group by time_id ORDER BY start, sch_name asc
```

**Comment by pihome-shc** [comment]
fixed this issue, can you test this and if it works lets close this issue

**Comment by sandreialexandru** [comment]
It is working...in some way. After clicking the circle the schedule still remains active in ../schedule.php, but with no zone selected

**Comment by pihome-shc** [comment]
yes schedule time still stay active but zone become in-active hence you see schedule time active.

**Comment by sandreialexandru** [comment]
Good enough solution for now, thank you! Do you agree that this issue can be closed? Please make a commit to the GITHUB code.

**Comment by pihome-shc** [comment]
yes, you can close this issue github is updated
