### ISSUE TITLE
ZONE overrun

### ISSUE THREAD

**Issue by sandreialexandru** [pihome-shc/pihome#429]
Having a zone valve open for some time, after the boiler stops would be a good idea. This helps with the dissipation of heat and the prevention of pressure building up.
CASE 1:
 If boiler is triggered by zone valve, then boiler overrun is the way to prevent pressure build-up, if the recirculation pump can be managed separately.
CASE 2:
If boiler is triggered by GPIO, then as soon as boiler stops the zone valve closes(triggered by GPIO or Zone Controller), but residual heat will not be dissipated and pressure would build.

**Comment by pihome-shc** [comment]
we already have implemented this: boiler stops first and takes reading from boiler table for overrun time and leave zone valve open but if anyone have boiler controlled by zone valve we have no way of offering control over that other then user have separate controller for boiler. or alternately user can disable this and have overrun loop (as i belive all systems have this)

**Comment by sandreialexandru** [comment]
Are you saying that if boiler is controlled by GPIO and zones are controlled by Wireless Zone Controllers, the valves remain open after the boiler stops?

**Comment by pihome-shc** [comment]
yes, that is the idea and i have my system controlled by gpio and it works

**Comment by sandreialexandru** [comment]
Great! I think I missunderstood the code. Sorry for that.

**Comment by pihome-shc** [comment]
no worries, if no further actions required can you close this issue
