### ISSUE TITLE
Error in PiHome_Temperature_Sensor_v035.ino.ino

### ISSUE THREAD

**Issue by twa127** [pihome-shc/pihome#437]
Hi,

The current version of PiHome_Temperature_Sensor_v035.ino.ino does not compile. I think the error was introduced with commit #430. The syntax for the line sensors.setResolution(TEMPERATURE_PRECISION); appears to be incorrect as the documentation indicates it requires a sensor address together with the precision value. 

As the default precision for the DS18b20 is 12bits anyway, is this update redundant ?

Can I also suggest the file name is tied-up from .ino.ino to .ino

**Comment by dvdcut** [comment]
i can not compile sketch either with line 
`sensors.setResolution(TEMPERATURE_PRECISION);`

**Comment by pihome-shc** [comment]
@twa127 i agree, my sensors report reading in 12bit as well, @sandreialexandru can you compile code or is there anything else wrong with your sensors?

**Comment by pihome-shc** [comment]
as example of my system temperature reading. 
![image](https://user-images.githubusercontent.com/33334232/99595483-b32ca400-29ec-11eb-9744-679ab63581c4.png)

**Comment by sandreialexandru** [comment]
I have found this solution after I had problems with 3 sensors. First I thought that one of them was broken, but after testing 2 more the results were the same. The code that I gave you is the one that I compiled for my sensor. I had no problems compiling.
Maybe a batch of DS18B20 is faulty, because not one but 3 of them defaulted to resolution 9, which I believe means that temperature readings are in 0.5 increments.

**Comment by pihome-shc** [comment]
may be sensors have resolution set different for your, what version of library you are using? 
onewire, mysensors etc.

**Comment by sandreialexandru** [comment]
OneWire version 2.3.5
DallasTemperature version 3.9.0
MySensors version 2.3.2

**Comment by twa127** [comment]
If you look in DallasTemperature.h there are 2 definitions for setResolution -

	// set global resolution to 9, 10, 11, or 12 bits
	void setResolution(uint8_t);

and

	// set resolution of a device to 9, 10, 11, or 12 bits
	bool setResolution(const uint8_t*, uint8_t,
			bool skipGlobalBitResolutionCalculation = false);

So it looks like you can set it globally, strange why it won't compile for me, my libraries are up to date

**Comment by pihome-shc** [comment]
i have following version and i can not compile it either, but funny thing is i have global resolution 8bit but i get 12bit resolution 

DallasTemperature version 3.7.2
MySensors version 2.3.2

**Comment by twa127** [comment]
I think sensors.setResolution(TEMPERATURE_PRECISION); is in the wrong place in the sketch. If you move it into void setup() after the line sensors.setWaitForConversion(false); then the sketch compiles okay.

**Comment by twa127** [comment]
Tried setting the global resolution to 9, 10, 11 and 12 bits and then captured the conversion time for each resolution, the results were 94, 188, 375 and 750 as per ds18b20 spec. I'll update the temperature sensor sketches if you think this is okay.

**Comment by pihome-shc** [comment]
I think its ok to update sketch,

**Comment by twa127** [comment]
Okay done both the NRF and RFM versions
