### ISSUE TITLE
Bug-Missing e-mail address!!! 

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/pihome#440]
When i tried to update email address on home page i get following error in console (firefox console) and email does not get updated.  can someone try this, i have received complains from users as well. 

update_email: Error.
jqXHR: [object Object]
textStatus: error
errorThrown:

**Comment by twa127** [comment]
Please let me know if committed fix helps

**Comment by pihome-shc** [comment]
this fixed the issue.
