### ISSUE TITLE
DB Cleanup Error: Permission Denied and The automatic update for temperature is not working

### ISSUE THREAD

**Issue by imammashur** [pihome-shc/pihome#453]
Hello there.

I got 2 errors.

1. When I go to the web server and see the cron jobs from the system status, the DB Cleanup returns Error: Permission Denied. Even though I change the permission just like the information, I still got an error.
2. In the dashboard, my temperature monitor for my zone is not changing until I run the command python /var/wwww/cron/gpio_ds18b20.py, is there a way to update the temperature automatically?

Thank you.

**Comment by pihome-shc** [comment]
@imammashur did you download img file form PiHome website? change changes made to database permission? 
on temperature sensors you need to un-comment following line from crontab 

`*/1 * * * * python /var/www/cron/gpio_ds18b20.py >/dev/null 2>&1`

**Comment by imammashur** [comment]
@pihome-shc yes i download it from the website. how do I change the permission? I have send sudo chmod -R 777 to all the files and follow the instruction that assigned on the webserver but I still got permission denied.

Thank you for the temperature sensors, it works now.

**Comment by pihome-shc** [comment]
@imammashur if img file is downloaded from PiHome website then you dont need to make any changes, no harm running follwoing two commands

```
chown -R www-data /var/www
chgrp -R www-data /var/www
```

**Comment by pihome-shc** [comment]
@imammashur any further action required?
