### ISSUE TITLE
Email Alert: Gmail option?

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/pihome#48]
Great project and very impressive GUI, Thank you for sharing with us. 
I have tried to get alerts setup with my Gmail account without any success, I can see on main page when zone/boiler controller or sensor isn’t reporting for set time but no email alerts. 

Do you have any plane to implement PHPMailer? i see you have older version of PHPMailer "class.phpmailer.php" but can not locate its reference anywhere.

**Comment by pihome-shc** [comment]
@dvdcut, 
yes i had plan to implement phpmailer but right now i m using python script done by one user which one added by @twa127

**Comment by pihome-shc** [comment]
@dvdcut doing backup take some time and so far its timed out on me twice i think best to call start_backup.php to run in background. 
`shell_exec("nohup php start_backup.php"); `

**Comment by pihome-shc** [comment]
@dvdcut i had implemented this for myself from PiHome email address and it worked ok, but most of the ISPs block sending email to prevent spam. i m not sure if this can be progressed any further, i have plans to implement this through PiConnect once new version become available.

**Comment by dvdcut** [comment]
@pihome-shc i agree with you,  i have same issues with sending email, this can not be progressed further as every one will have same issues. closing this issue.
