### ISSUE TITLE
Edit Node Alert Settings

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/pihome#50]
option to edit alert settings for each node. sorry i have to attached file github is messing up my code. 
But i can not get it to work, maybe someone else can look at this. 
[node_alert.txt](https://github.com/pihome-shc/pihome/files/3535629/node_alert.txt)

**Comment by pihome-shc** [comment]
@dvdcut your code looks ok to me it loads all nodes alert settings but making change part isnt working and in console i can see it only submit value for first node regardless what option or node you try to change. i'll try to go through your code later in the evening.

**Comment by twa127** [comment]
See #55, uses a table to display node alert settings and enable edit of the notice_interval value

**Comment by pihome-shc** [comment]
This issue is fixed now, thanks to @dvdcut and @twa127 for working on this.
