### ISSUE TITLE
Process to update PiHome and Database. 

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/pihome#57]
I can see icon for PiHome Updates under setting but nothing implemented to update/pull code from GitHub or update database.

For code it would be easy to have script to run `git pull origin` once a while but how to update database? and how to keep track of older version i.e. let’s say if I miss one update I can get code updated to latest and greats but how to gradually update database? 

I m just throwing this idea out to see what others think.

**Comment by pihome-shc** [comment]
@dvdcut yes i had plan to implement updates but never had time to work on this, sure we can get some idea going, its not high priority in my list but i can make some room for this.

**Comment by twa127** [comment]
Just giving this some thought and got a question - what is all the VIEW related stuff for towards the bottom of pihome_mysql_database.sql, I assumed that the VIEWs were setup from either MySQL_View.sql or setup_db.php

**Comment by twa127** [comment]
I'm testing a script which compares a mysqldump file of the structure of the installed pihome database against the GITHUB file pihome_mysql_database.sql and generates an sql file of ALTER/DROP/CREATE statements to update the local database.

**Comment by pihome-shc** [comment]
@twa127 that would be one great if we can get something working for database.

**Comment by twa127** [comment]
Do you want to give this a try, it is based around the existing setup_db.php. 

Install update_db.txt as  update_db.php in MySQL_Database and dbStruct.txt as dbStruct.php in st_inc

It checks a a mysqldump of the installed database table structure against the repository file pihome_mysql_database.sql and generates an update file. Does not do anything about updating the VIEWs.

Note: it will identify the issues I found with the current version of pihome_mysql_database.sql

[dbStruct.txt](https://github.com/pihome-shc/pihome/files/3619581/dbStruct.txt)
[update_db.txt](https://github.com/pihome-shc/pihome/files/3619582/update_db.txt)

**Comment by pihome-shc** [comment]
@twa127 
that is some amount of code. sorry i haven't tested very busy these days. but i will try to get to this tomorrow evening.

**Comment by twa127** [comment]
No problem, please let me know what you think, I'll post one further small change to pihome_mysql_database.sql, there is a redundant field 'ACTIVE' in the holidays table, 'STATUS' is now used instead.

**Comment by pihome-shc** [comment]
@twa127 
script worked on my centos installation even when i delete on my local database and it pulls and fix that deletion. 
however right now i just powered on RPI and on execution i get following over and over even after i execute sql statement from phpmyadmin for away table. 
here my database. also best to remove currentDB_dump.sql at the end of script. 
[pihome_2019-09-20_18-56-51.zip](https://github.com/pihome-shc/pihome/files/3637171/pihome_2019-09-20_18-56-51.zip)




2019-09-20 18:58:50 - The Following Updates will be Applied to the Database.
2019-09-20 18:58:50 - ALTER TABLE `away` MODIFY `away_button_child_id` int(11) DEFAULT '4';
2019-09-20 18:58:50 - ALTER TABLE `away` MODIFY `away_button_id` int(11) DEFAULT '40';
2019-09-20 18:58:50 - ALTER TABLE `away` MODIFY `start_datetime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
2019-09-20 18:58:50 - ALTER TABLE `boiler` MODIFY `datetime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
2019-09-20 18:58:50 - ALTER TABLE `boiler` MODIFY `fired_status` tinyint(4) DEFAULT '0';
2019-09-20 18:58:50 - ALTER TABLE `boiler` MODIFY `hysteresis_time` tinyint(4) DEFAULT '3';
2019-09-20 18:58:50 - ALTER TABLE `boiler` MODIFY `max_operation_time` tinyint(4) DEFAULT '60';
2019-09-20 18:58:50 - ALTER TABLE `boiler` MODIFY `node_child_id` int(11) DEFAULT '1';
2019-09-20 18:58:50 - ALTER TABLE `boiler` MODIFY `status` tinyint(4) DEFAULT '0';
2019-09-20 18:58:50 - ALTER TABLE `boost` MODIFY `minute` tinyint(4) DEFAULT '30';
2019-09-20 18:58:50 - ALTER TABLE `boost` MODIFY `status` tinyint(4) DEFAULT '0';
2019-09-20 18:58:50 - ALTER TABLE `boost` MODIFY `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
2019-09-20 18:58:50 - ALTER TABLE `frost_protection` MODIFY `datetime` timestamp NULL DEFAULT CURRENT_TIMESTAMP;
2019-09-20 18:58:50 - ALTER TABLE `frost_protection` MODIFY `temperature` float NOT NULL DEFAULT '5';
2019-09-20 18:58:50 - ALTER TABLE `gateway` MODIFY `find_gw` tinyint(4) DEFAULT '0';
2019-09-20 18:58:50 - ALTER TABLE `gateway` MODIFY `reboot` tinyint(4) DEFAULT '0';
2019-09-20 18:58:50 - ALTER TABLE `gateway_logs` MODIFY `pid_datetime` timestamp NULL DEFAULT CURRENT_TIMESTAMP;
2019-09-20 18:58:50 - ALTER TABLE `messages_in` MODIFY `datetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
2019-09-20 18:58:50 - ALTER TABLE `messages_out` MODIFY `datetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Current datetime';
2019-09-20 18:58:50 - ALTER TABLE `mqtt` MODIFY `enabled` TINYINT(4) NOT NULL DEFAULT '1';
2019-09-20 18:58:50 - ALTER TABLE `mqtt` MODIFY `port` INT(11) NOT NULL DEFAULT '1883';
2019-09-20 18:58:50 - ALTER TABLE `nodes` MODIFY `last_seen` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP;
2019-09-20 18:58:50 - ALTER TABLE `nodes` MODIFY `notice_interval` int(11) NOT NULL DEFAULT '30';
2019-09-20 18:58:50 - ALTER TABLE `nodes_battery` MODIFY `update` timestamp NULL DEFAULT CURRENT_TIMESTAMP;
2019-09-20 18:58:50 - ALTER TABLE `notice` MODIFY `datetime` timestamp NULL DEFAULT CURRENT_TIMESTAMP;
2019-09-20 18:58:50 - ALTER TABLE `override` MODIFY `status` tinyint(4) DEFAULT '0';
2019-09-20 18:58:50 - ALTER TABLE `override` MODIFY `temperature` tinyint(4) DEFAULT '22';
2019-09-20 18:58:50 - ALTER TABLE `override` MODIFY `time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
2019-09-20 18:58:50 - ALTER TABLE `schedule_daily_time` MODIFY `WeekDays` smallint(6) NOT NULL DEFAULT '127';
2019-09-20 18:58:50 - ALTER TABLE `schedule_daily_time_zone` MODIFY `temperature` float NOT NULL DEFAULT '0';
2019-09-20 18:58:50 - ALTER TABLE `schedule_night_climat_zone` MODIFY `max_temperature` float NOT NULL DEFAULT '21';
2019-09-20 18:58:50 - ALTER TABLE `schedule_night_climat_zone` MODIFY `min_temperature` float NOT NULL DEFAULT '18';
2019-09-20 18:58:50 - ALTER TABLE `system` MODIFY `reboot` tinyint(4) DEFAULT '0';
2019-09-20 18:58:50 - ALTER TABLE `system` MODIFY `shutdown` tinyint(4) DEFAULT '0';
2019-09-20 18:58:50 - ALTER TABLE `user` MODIFY `cpdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
2019-09-20 18:58:50 - ALTER TABLE `userhistory` MODIFY `audit` tinytext;
2019-09-20 18:58:50 - ALTER TABLE `userhistory` MODIFY `ipaddress` tinytext;
2019-09-20 18:58:50 - ALTER TABLE `weather` MODIFY `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last weather update';
2019-09-20 18:58:50 - ALTER TABLE `zone` MODIFY `graph_it` tinyint(1) NOT NULL DEFAULT '1';
2019-09-20 18:58:50 - ALTER TABLE `zone` MODIFY `sp_deadband` float NOT NULL DEFAULT '0.5';
2019-09-20 18:58:50

**Comment by twa127** [comment]
Hi,

pihome_2019-09-20_18-56-51.zip does not have the updates I posted over the last few days, in particular the DEFAULT values need to be enclosed in single quotes, e.g. `away_button_id` int(11) DEFAULT 40, should read `away_button_id` int(11) DEFAULT '40', Are you running the script to check against a local copy of the database rather than on one on GITHUB?

I left currentDB_dump.sql so that you could always go back and check what modifications were last execucuted but could be deleted if that's not required.

**Comment by pihome-shc** [comment]
Hi, 
yes thats right pihome_2019-09-20_18-56-51.zip is older version and i was checking against GitHub. to see if it pulls updates from GitHub.

**Comment by twa127** [comment]
Hi,
The way the script is setup is that it creates a copy of the operating database table structures using mysqldump, it then compares this against the current copy of pihome_mysql_database.sql on GITHUB to generate the update SQL. There were a number of issues with pihome_mysql_database.sql, which have been fixed over the last few days.

I guess you are getting the list of updates on your RPI is because you are comparing against your local copy and not GITHUB

**Comment by twa127** [comment]
mysqldump on my machine (BeagleBone running Debian/stretch) produces numeric DEFAULT values in single quotes ie DEFAULT '0', but looks like mysqldump on your RPI is producing as DEFAULT 0,

I don't know why that is happening, I'll try setting up a RPI and seeing if I can reproduce your results.

**Comment by pihome-shc** [comment]
@twa127 good thing about this script is: **it works**, i have done following tests:

- delete some tables and executed this script and it re-created those tables. 
- deleted column and it re-created them successfully. 
- next i will empty all the database to see if it works, i m sure i will. 

on DEFAULT values in single quotes ie DEFAULT '0' or DEFAULT 0 what version of MySQL you have? what happens if DEFAULT 0 on your system?

**Comment by twa127** [comment]
mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2

it accepts DEFAULT values with or without quotes, just mysqldump output uses the single quotes in the dump

**Comment by pihome-shc** [comment]
where what it shows me on screen yes it is with '0' 

2019-09-20 21:34:39 - ALTER TABLE `away` MODIFY `away_button_child_id` int(11) DEFAULT '4';
2019-09-20 21:34:39 - ALTER TABLE `away` MODIFY `away_button_id` int(11) DEFAULT '40';
2019-09-20 21:34:39 - ALTER TABLE `away` MODIFY `start_datetime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

**here is dump for same** 
  `start_datetime` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `away_button_id` int(11) DEFAULT 40,
  `away_button_child_id` int(11) DEFAULT 4,

**here is MySQL Server on RPI**
    Server: Localhost via UNIX socket
    Server type: MariaDB
    Server version: 10.3.15-MariaDB-1 - Raspbian testing-staging
    Protocol version: 10
    Server charset: UTF-8 Unicode (utf8)

**Comment by twa127** [comment]
Okay just loaded an RPI with the SD card image
mysqldump gives:

`start_datetime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`away_button_id` int(11) DEFAULT '40',
`away_button_child_id` int(11) DEFAULT '4',

are your **here is dump for same** lines coming from myssqdump?

**Comment by pihome-shc** [comment]
yes that is right, see below once more same result,

  `start_datetime` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `away_button_id` int(11) DEFAULT 40,
  `away_button_child_id` int(11) DEFAULT 4,

**Comment by twa127** [comment]
Hi,

Very strange, I'm dumping with **mysqldump -u root -ppihome2018 pihome > dump.sql**

**Comment by pihome-shc** [comment]
**mysqldump -u root -ppihome2018 pihome > dump.sql** produce same result 
  `away_button_id` int(11) DEFAULT 40,
  `away_button_child_id` int(11) DEFAULT 4,

:(

**Comment by twa127** [comment]
very strange eh :(

tried to see if there are any mysqldump defaults setup:

root@raspberrypi:~# mysqldump --print-defaults
mysqldump would have been started with the following arguments:
--quick --quote-names --max_allowed_packet=16M --default-character-set=utf8mb4

**Comment by pihome-shc** [comment]
root@pihome:/var/www/MySQL_Database# mysqldump --print-defaults
mysqldump would have been started with the following arguments:
--quick --quote-names --max_allowed_packet=16M --default-character-set=utf8mb4 --socket=/var/run/mysqld/mysqld.sock

**Comment by twa127** [comment]
not that then :(

I'll sleep on it, perhaps it will come to me in a dream :-))

**Comment by pihome-shc** [comment]
not sure it matters but my database default collation is **utf8mb4_general_ci**

**Comment by twa127** [comment]
I'll try loading your zip file and then see how that dumps

**Comment by twa127** [comment]
let you know in the morning

**Comment by twa127** [comment]
Morning,

I loaded your pihome_2019-09-20_18-56-51.zip into my RPI and then dumped with **mysqldump -u root -ppihome2018 pihome > dump.sql**

Looking at the dump file produced the format is not the same as you're getting, below is the away table:

DROP TABLE IF EXISTS `away`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `away` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sync` tinyint(4) NOT NULL DEFAULT '0',
  `purge` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'Mark For Deletion',
  `status` tinyint(4) DEFAULT NULL,
  `start_datetime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `end_datetime` timestamp NULL DEFAULT NULL,
  `away_button_id` int(11) DEFAULT '40',
  `away_button_child_id` int(11) DEFAULT '4',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf16 COLLATE=utf16_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

If I run the update script against your copy of the database I get:
ALTER TABLE `holidays` DROP `active`;

If I let it make the change then run it again it does not find any further changes.

So just can't understand why mysqldump on your RPI is giving different results :)

**Comment by pihome-shc** [comment]
good morning, i think its ok, i dont think its major issue, and it wouldn't cause any problems either, just need to make some rules for future pull request to have default value as DEFAULT '4',

**Comment by pihome-shc** [comment]
Huston we have a problem: 
after executing update_db.php all default values are set to No default specially sync and purge and this is causing problem.

**Comment by twa127** [comment]
Not seeing that, can you see what's making those changes in currentDB_dump.sql

**Comment by pihome-shc** [comment]
i have done one more test, 
crated database from scratch (CREATE DATABASE `` /*!40100 COLLATE 'utf16_bin' */) 
imported sql from from GitHub to create new database so this should not requires any further updates but when i run update_db.php it still thinks following changes required and set to default values to No Default. (see First_Time_Update.txt file)  after applying change second time run shows only few changes and majorities of these are for default '0' (see Second_Update.txt)

[First_Time_Update.txt](https://github.com/pihome-shc/pihome/files/3638647/First_Time_Update.txt)
[Second_Update.txt](https://github.com/pihome-shc/pihome/files/3638648/Second_Update.txt)

**Comment by twa127** [comment]
Huston to Apollo 13

Think I've identified the problem. 

I've just update using your latest sd card image which gives me mysql  Ver 15.1 Distrib 10.3.15-MariaDB rather than Distrib 10.1.26-MariaDB on my BeagleBone. If I run mysqldump now I get the DEFAULT values without quotes and the DATETIME with (), so obviously something to do with the difference in versions,

If I run the update script I get the same results as you, so need to find someway to make it compatible with both versions. The easiest solution would be to find some way of making mysqldump produce outputs in the same format for both versions.

**Comment by pihome-shc** [comment]
if we have default value DEFAULT 0 ranter then DEFAULT '0' does it work with your version of sql? but again need to find solution to this problem

**Comment by twa127** [comment]
No DEFAULT 0 rather then DEFAULT '0' does not work with the older version of MariaDB, this is why I made all the recent changes to pihome_mysql_database.sql 

The other option is to find a way of updating MariaDB on my BB

**Comment by twa127** [comment]
It appears that from MariaDB 10.2.3, expressions are accepted in the DEFAULT clause, so guess that's why the format change in mysqldump

I think the best way forward is for me to find a way of updating MariaDB and the chance the formate of pihome_mysql_database.sql back to match the current mysqldump format.

I'll make the changes, test and let you know

**Comment by twa127** [comment]
Okay I'll post an update to the database which reverses out the last few changes.

Give the update a try

**Comment by pihome-shc** [comment]
@twa127 thank you, your pull request, this updated fixed the issue. 
now how to implement this process from web interface. 

how i m updating my deployment to latest 
sudo git clone https://github.com/pihome-shc/pihome "/var/www"
cd /var/www
git pull origin

may be there is better way, i.e first do full backup of database and code and then update.

**Comment by twa127** [comment]
Hi

Away for a couple of weeks, I've just updated from STRETCH to BUSTER to get my database up to your version

**Comment by dvdcut** [comment]
@twa127 @pihome-shc  
any updates on this? i m using default img file from pihome website and its working for me. may be you can add this feature for img file only 
dbStruct.php
update_db.php

**Comment by twa127** [comment]
Hi,

I've not done anymore on this at the moment, the aim was use it from the WEB interface, but not there yet. 
I've just used it to update my database to include the latest changes. It would be good if it also updates the views, but not worked that out yet.

I'll raise a commit to include dbStruct.php and update_db.php in to the code base.

**Comment by pihome-shc** [comment]
fixed single file database login credentials and added option to update versions and build even if there isnt any database update available.

**Comment by pihome-shc** [comment]
Comments by Users on PiHome website 
[link ](http://www.pihome.eu/2020/01/26/pihome-version-1-70/#comment-5174)
It looks to me like the git master and dev branches as well as the pihome-1.70.tar.gz tarball all have an identical setup.php. I haven’t done exhaustive debugging on this (I just don’t have the SQL or PHP skills at this point), but at least the zone_view and schedule_daily_time_zone_view don’t match boiler.php. I can attempt to do the debugging myself if it’s really something that needs to be done and matching versions don’t exist. You’ll have to be patient with me, though, it could take a while!
Thanks again.

**Comment by dvdcut** [comment]
Database update process is working without any issues. i m closing this, may be we can do something about code update in MaxAir

**Comment by twa127** [comment]
Hi,

I've got an experimental code update python script, use with care as it updates /var/www

[update_code.zip](https://github.com/pihome-shc/pihome/files/6051980/update_code.zip)

**Comment by pihome-shc** [comment]
@twa127 that worked without any issue. can we have this issue in MaxAir repository

**Comment by twa127** [comment]
okay will do

**Comment by twa127** [comment]
If using with pihome version 1 you will need to change the repository at line 81

from os.system('sudo git clone https://github.com/pihome-shc/PiHomeHVAC.git ' + source_dir)
to os.system('sudo git clone https://github.com/pihome-shc/pihome.git ' + source_dir)

**Comment by pihome-shc** [comment]
Can I initiate this process from web?

**Comment by twa127** [comment]
How do you mean, from within pihome or via a url ?
