### ISSUE TITLE
Ability to Add/Edit & Delete Exiting Boost options

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/pihome#61]
## Settings
@dvdcut added option on GUI to add/delete boost options this can be improved with edit on the screen.

**Comment by pihome-shc** [comment]
@twa127 
just noticed one thing on query, have look at following query, i think it would display better and order better, what do you think? 

select boost.id, boost.`status`, boost.sync, boost.zone_id, zone_idx.index_id, zone.name, boost.temperature, boost.minute, boost.boost_button_id, boost.boost_button_child_id
from boost
join zone on boost.zone_id = zone.id
join zone zone_idx on boost.zone_id = zone_idx.id
ORDER BY zone.index_id ASC, boost.minute ASC;

**Comment by twa127** [comment]
That's a good idea, I had not considered how zones with multiple boosts would display

**Comment by dvdcut** [comment]
I m unable to modify boost settings after your last pull request i can see request.js changes, i”ll report back when i get home later for more detailed error.

**Comment by twa127** [comment]
Okay please let me know, seems to work okay in EDGE and SAFARI

**Comment by twa127** [comment]
The bug is in db.php, where I've truncated a line of code

**Comment by pihome-shc** [comment]
@twa127 that is great and tested in Firefox and in Edge, only issue i m having right now in Edge is when click on add boost it just refresh settings.php page but it works in Firefox so not sure why MS Edge is causing this.

**Comment by twa127** [comment]
I see the same with EDGE, works okay with IE and SAFARI

**Comment by pihome-shc** [comment]
@twa127 
i think its ok, i'm closing this ticket. if needed new issue can be created.
