### ISSUE TITLE
Nodes options

### ISSUE THREAD

**Issue by harvybob** [pihome-shc/pihome#70]
Add node options i.e gpio pin treated as node and i2c relay board treated as node and have option under settings to add these nodes manually.

**Comment by dvdcut** [comment]
I been thinking about this issue and I think following will fix it:
Add column for 'type' in nodes table before node id. 
as of today i see there types of nodes: Wireless, GPIO, I2C, 
remove gpio from boiler and zone table, 
boiler_view and zone_view should change to include nodes.type 
boiler.php as of today from [line 322](https://github.com/pihome-shc/pihome/blob/fba5cdafaa61e34d36deb5163a07a03e4e65c069/cron/boiler.php#L322) need to be changed and execute command based on type,

**Comment by dvdcut** [comment]
one more thing wifigw.py and serial.py needs to be changed as well to add type wireless and I think in future this might help to implement MQTT as well. 
under setting new icon is required to give user option to create nodes either GPIO, i2c, or even in future some esp8266 or esp32 or any other wired or wireless technology. 

on same note I suggest to be careful with names in type field as wifi could be esp or mysensors wireless

**Comment by pihome-shc** [comment]
@dvdcut thank you for your input, i have completed work on boiler.php, database and table view, now modifying settings (model.php)

**Comment by pihome-shc** [comment]
this issue is closed no further updates required.
