### ISSUE TITLE
Automatic Loop for hotwater for graphs 

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/pihome#77]
## Automatic Loop for hot water for graphs 
If user have 1-Wire DS18B20 temperature sensors connected to Raspberry pi GPIO then graph for Hot water wouldn't show and need code modification i.e. charlist.php and modify node id to respective 1-Wire temperature sensor id to get graph drawn in web interface. 
### Suggestion
Change the code same as zone and loop through the zones set as hot water 
### Example
look in [chartfooter.php](https://github.com/pihome-shc/pihome/blob/master/chartfooter.php) from line 46 to 119

**Comment by dvdcut** [comment]
works great but one small issue. in hot water graph it also drawing outside weather temperature.

**Comment by dvdcut** [comment]
ok fix was easy, [line 165 in chartfooter.php](https://github.com/pihome-shc/pihome/blob/db2e437c66a2c0cb42addfdd24e208c7064ff729/chartfooter.php#L165) just comment it out to remove weather graph from hot water. 

`echo "{label: \"".$lang['graph_outsie']."\", data: ".json_encode($weather_c).", color: rainbow(".$count.",".++$counter.") }, \n";`

i m no expert in java but i think you don't need to copy/redefine rainbow function for hot water graph as its already done in heating zone.
