### ISSUE TITLE
Boost Console/Button

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/pihome#78]
while i was testing buffer tank setup i noticed boost button console id and boost button id don't get updated if you change them in model, i think only workaround this is to disable them but if user want then user need to create new boost entry with correct boost console id and boost button. its small bug if you are using boost console and want to make some modifications.

**Comment by pihome-shc** [comment]
@dvdcut i think disabling edit option for boost button console is the only option i can think of.

**Comment by dvdcut** [comment]
Hi, 
i think #211 is the only way how to fix this, if you can think of some better way then let me know.

**Comment by pihome-shc** [comment]
@dvdcut i see what you mean, solution is working so lets keep it that way.
