### ISSUE TITLE
Email setup for Node alert

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/pihome#82]
small bug:
i try to setup email under e-mail alert and its not saving any setting, i did some investigation and found that query in db.php only updating record and not searching if record exit or not. 

`$query = "UPDATE email SET smtp = '".$e_smtp."', username = '".$e_username."', password = '".$e_password."', `from` = '".$e_from_address."', `to` = '".$e_to_address."', status = '".$status."' where ID = 1;";`

**Comment by pihome-shc** [comment]
Closing this as update provided by @dvdcut  worked.
