### ISSUE TITLE
unable to view schedules

### ISSUE THREAD

**Issue by harvybob** [pihome-shc/pihome#87]
Hi all, not sure if its me (ie browser/my setup) but i am unable to see schedules. When i create one, i can create by selecting zones etc, but i cant then view them. If i check in maria, i can see it, but not on the GUI?

I have taken a clone from git hub as it is now (23:00 on Thursday 2nd Jan GMT), and overwrote all files in my /var/www + updated the sql connection details and run the update_db.php script.

Am i missing something?

**Comment by pihome-shc** [comment]
@harvybob 
can you try to create table view as per [MySQL_View.sql](https://github.com/pihome-shc/pihome/blob/master/MySQL_Database/MySQL_View.sql)

**Comment by harvybob** [comment]
CREATE VIEW schedule_daily_time_zone_view AS
select ss.id as time_id, ss.status as time_status, sstart.start, send.end, sWeekDays.WeekDays,
sdtz.sync as tz_sync, sdtz.id as tz_id, sdtz.status as tz_status,
sdtz.zone_id, zone.index_id, zone.name as zone_name, zt.`type`, temperature, holidays_id , coop, ss.sch_name
from schedule_daily_time_zone sdtz
join schedule_daily_time ss on sdtz.schedule_daily_time_id = ss.id
join schedule_daily_time sstart on sdtz.schedule_daily_time_id = sstart.id
join schedule_daily_time send on sdtz.schedule_daily_time_id = send.id
join schedule_daily_time sWeekDays on sdtz.schedule_daily_time_id = sWeekDays.id
join zone on sdtz.zone_id = zone.id
join zone zt on sdtz.zone_id = zt.id
where sdtz.`purge` = '0' order by zone.index_id

MySQL said: Documentation
#1054 - Unknown column 'ss.sch_name' in 'field list'

**Comment by harvybob** [comment]
im guessing my database didnt update correctly so starting again... close this issue.
