### ISSUE TITLE
single non updated config file for database ip/user/pass

### ISSUE THREAD

**Issue by harvybob** [pihome-shc/pihome#88]
Hi, is someone able to adjust to allow for a single config file which can be user created to provide connection details for the database? Then slowly we can point anything that needs database access to use that single file rather then have connection details in multiple files?

Github has an option of ignoring specified files, so if/when someone then does a commit, that file is not pushed up, and likewise not overwritten when pulled down

**Comment by sandreialexandru** [comment]
I believe you are reffering to **/st_inc/_config.inc.php**

**Comment by harvybob** [comment]
Thanks, looks like the setup.php, the MySQL_database\setup_db.php and MySQL_database\update_db.php have been missed.

**Comment by sandreialexandru** [comment]
I've issued pull requests with changes into all files mentioned. There are 2 files that need to be changed by the user, with database credentials: **/st_inc/_config.inc.php** & **/cron/py_access.py**. py_access.py needs to be changed at line 8.

**Comment by pihome-shc** [comment]
@sandreialexandru two more file need modification /var/www/cron/wifigw.py and /var/www/cron/serialgw.py

**Comment by pihome-shc** [comment]
@twa127 
is there any depency required for ini file to work in python? here is output i have when i try to run wifigw.py 

`Traceback (most recent call last):
  File "/var/www/cron/wifigw.py", line 43, in <module>
    dbhost = config.get('db', 'hostname')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'db'`

**Comment by pihome-shc** [comment]
on same note, may be best to place db_config.ini in /var/www/st_inc/ folder.

**Comment by twa127** [comment]
Hi

Not that I know of, runs fine on my beaglebone, I try it on a PI.

**Comment by twa127** [comment]
True, do you have the first line [db] in the .ini

**Comment by twa127** [comment]
It is a Pi thing, I’ll recode and update

**Comment by pihome-shc** [comment]
ok, i think i know what wrong, Paths are relative to the current working directory, which is usually the directory from which you run your program, i have to be in /var/www/cron folder and then i can run python wifigw.py, cron job run script works ok but when i try to run this python script i have to be in that folder. 


### second issue:
i have default login credentials slightly different then yours. i would go for first option. as all of them installation have this default password and updates can be deployed without breaking any one's system but i m open to suggestions. 


#### option 1:
```
[db]
hostname = localhost
dbusername = root
dbpassword = passw0rd
dbname = pihome
connect_error = Sorry We are Experiencing MySQL Database Connection Problem...
```

#### option 2:
```
[db]
hostname = localhost
dbusername = pihomedbadmin
dbpassword = pihome2018
dbname = pihome
connect_error = Sorry We are Experiencing MySQL Database Connection Problem...
```

**Comment by sandreialexandru** [comment]
I have just tested the new setup, with only one config file and I had problems connectig to database. Managed to make it work by using apostrophes for values in .ini file
```
[db]
hostname = 'localhost'
dbusername = 'pihomedbadmin'
dbpassword = 'pihome2018'
dbname = 'pihome'
connect_error = 'Sorry We are Experiencing MySQL Database Connection Problem...'
```

**Comment by sandreialexandru** [comment]
For python connection to database it is best to use variable names as described in manual
user
password or passwd
host
database or db

**Comment by sandreialexandru** [comment]
> @twa127
> is there any depency required for ini file to work in python? here is output i have when i try to run wifigw.py
> 
> `Traceback (most recent call last): File "/var/www/cron/wifigw.py", line 43, in <module> dbhost = config.get('db', 'hostname') File "/usr/lib/python2.7/ConfigParser.py", line 607, in get raise NoSectionError(section) ConfigParser.NoSectionError: No section: 'db'`

From what I've read, an absolute path to the file **db_config.ini** must be used, not a relative one.

**Comment by twa127** [comment]
Hi

Relative is working okay for me, the main problem I think is that configparser work differently on the Pi than in my beagle one, now changed format so it works on both

**Comment by dvdcut** [comment]
i think there is problem with check_gw.php file now, i changed line 107 to following to get logs 

`exec("python /var/www/cron/wifigw.py  >>/var/www/cron/logs/check_gw.log 2>&1");`

and changed crontab as well to get these logs. 
`*/1 * * * * php /var/www/cron/check_gw.php >>/var/www/cron/logs/check_gw.log 2>&1`
to produce following output, i think since introduction of single non updated config file it has broken my installation. 

```
[36m
   _____    _   _    _                             
  |  __ \  (_) | |  | |                            
  | |__) |  _  | |__| |   ___    _ __ ___     ___  
  |  ___/  | | |  __  |  / _ \  | |_  \_ \   / _ \ 
  | |      | | | |  | | | (_) | | | | | | | |  __/ 
  |_|      |_| |_|  |_|  \___/  |_| |_| |_|  \___| 
 [0m 
     [45m S M A R T   H E A T I N G   C O N T R O L [0m 
[31m********************************************************
*   Gateway Script Version 0.3 Build Date 22/01/2018   *
*          Last Modification Date 29/06/2019           *
*                                Have Fun - PiHome.eu  *
********************************************************
 [0m 
[36m2020-01-20 00:46:02[0m - Python Gateway Script Status Check Script Started 
[36m2020-01-20 00:46:02[0m - Python Script for WiFi Gateway [41mNot Running[0m 
[36m2020-01-20 00:46:02[0m - Starting Python Script for WiFi Gateway 
[95m 
  _____    _   _    _                            
 |  __ \  (_) | |  | |                           
 | |__) |  _  | |__| |   ___    _ __ ___     ___ 
 |  ___/  | | |  __  |  / _ \  | |_  \_ \   / _ \ 
 | |      | | | |  | | | (_) | | | | | | | |  __/
 |_|      |_| |_|  |_|  \___/  |_| |_| |_|  \___|
 
    [3;30;45mS M A R T   H E A T I N G   C O N T R O L [0m
[0;31;40m 
********************************************************
* MySensors Wifi/Ethernet Gateway Communication Script *
* to communicate with MySensors Nodes, for more info   *
* please check MySensors API. Build Date: 18/09/2017   *
*      Version 0.08 - Last Modified 20/07/2019         *
*                                 Have Fun - PiHome.eu *
********************************************************
 [0m
Traceback (most recent call last):
  File "/var/www/cron/wifigw.py", line 40, in <module>
    dbhost = config.get('db', 'hostname')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'db'
PHP Notice:  Undefined offset: 0 in /var/www/cron/check_gw.php on line 112
[36m2020-01-20 00:46:02[0m - The PID is: [41m[0m 
PHP Notice:  Undefined offset: 0 in /var/www/cron/check_gw.php on line 113
error: list of process IDs must follow -p

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
PHP Notice:  Undefined offset: 0 in /var/www/cron/check_gw.php on line 114
PHP Notice:  Undefined offset: 0 in /var/www/cron/check_gw.php on line 117
--------------------------------------------------------------------------
[36m2020-01-20 00:46:02[0m - Python Gateway Script Status Check Script Ended 
[32m***************************************************************************[0m

```

**Comment by pihome-shc** [comment]
i think this issue is fixed, can this be closed.

**Comment by pihome-shc** [comment]
Closing this issue.
