### ISSUE TITLE
Schedule edit : temperatures get updated to 0

### ISSUE THREAD

**Issue by sandreialexandru** [pihome-shc/pihome#93]
Something strange is happening when editing schedules.
After adding  schedule, if trying to edit, all temperatures get updated to 0

**Comment by pihome-shc** [comment]
@sandreialexandru 
do you still have this issue or this issue is related to your pull request #92 View slider temperature. ?

**Comment by sandreialexandru** [comment]
Still the same. I can't figure out why $temp gets 0 value. Even if I revert everything to original, the problem persists. Anyone having this issue besides me?

**Comment by sandreialexandru** [comment]
Here is my test setup
autoaxe.ro/pihome

**Comment by pihome-shc** [comment]
@sandreialexandru 
just tested, addition works fine, but edit brings temperature to 0 on saving. but one clicking on Edit it is not loading temperature from database and its setting all enabled zone to default 15 value.

**Comment by sandreialexandru** [comment]
<output name="show_temp_val" id="temp<?php echo $row["zone_id"];?>" style="padding-top:0px !important; font-size:18px !important;">15.0</output>

Instead of 15.0 there should be a query to get database temperature, but I'm thinking this should not be the issue of updating temperatures to 0

**Comment by sandreialexandru** [comment]
Here are the 3 files modified in pull request 92 (footer.php, schedule_add.php and schedule_edit.php). Please have a look and see if you can replicate the problem. This is giving a hard time.

[Downloads.zip](https://github.com/pihome-shc/pihome/files/4079165/Downloads.zip)

**Comment by pihome-shc** [comment]
ok here are my finding:
footer.php
you have commented line 133 to 144 but this does not make any difference, 
`while ($row = mysqli_fetch_assoc($results)) { ?>` 
schedule_edit.php
line 89 i have changed show_temp_val to temp as this is reference in form. 
$temp=TempToDB($conn,$_POST['temp'][$id]);

In form itself i have changed 
value="15.0"
to
value="<?php echo DispTemp($conn, $row['temperature']) ?>"
second change
name="temp[<?php echo $row["zone_id"];?>]" 
to 
name="temp[<?php echo $row["tz_id"];?>

can you make these changes and test, also best to leave footer.php as it is.

**Comment by pihome-shc** [comment]
here is the fixed version of schedule_edit.php

[schedule_edit.zip](https://github.com/pihome-shc/pihome/files/4079678/schedule_edit.zip)

**Comment by sandreialexandru** [comment]
Fixed with latest pull request for schedule_edit.php. All working fine! Thank for support!

**Comment by sandreialexandru** [comment]
Please check my test setup
