### ISSUE TITLE
Weather Update API changed ?

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/pihome#95]
## Issue i received from one user:

Hi, just wanted to let the developers know that I had to make a mod to the weather_update.php file to get the function to work, I suspect this is due to changes in the API call at openweather.org.

In three places in the ‘sixdays’ code I had remove the ‘/daily’ to change, the ‘5 day/3hr’ section had already been updated.

`//$weather_sixdays_api = “http://api.openweathermap.org/data/2.5/forecast/daily?q=”.$city.”,”.$country.”&appid=”.$appid;`
to
`//$weather_sixdays_api = “http://api.openweathermap.org/data/2.5/forecast?q=”.$city.”,”.$country.”&appid=”.$appid;`

can any one test this, because its working for me without any change but it might be my api is older and new signup have this issue.

**Comment by harvybob** [comment]
I think daily is no longer free, just the 3 hour

**Comment by pihome-shc** [comment]
@harvybob Thank you for confirming this.

**Comment by pihome-shc** [comment]
Closing this issue.
